In [1]:
# run all the tools with agents and LLM model
from langchain_groq import ChatGroq
groq_api_key='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'
model=ChatGroq(model='Gemma-7b-It',groq_api_key=groq_api_key)
model

ChatGroq(client=<groq.resources.chat.completions.Completions object at 0x00000287D2A9D9D0>, async_client=<groq.resources.chat.completions.AsyncCompletions object at 0x00000287D2A8F6A0>, model_name='Gemma-7b-It', groq_api_key=SecretStr('**********'))

In [3]:
from langchain.schema import (AIMessage,HumanMessage,SystemMessage)

In [4]:
speech="""
Good morning to all of you present here. Today I am here to deliver a Speech on Life. Life is valuable. It is a gift to you from God. It's so special that there's no one else like you on Earth.   Existence, again, is a chance. It is a chance for good to be achieved. Therefore, it does not matter how long you live; how well you live is all that counts. And how many lives you, with love and encouragement, will affect.
Another idea is that death still shadows life. Everybody has to face it. He or she is a wise man or woman who, when it comes, is prepared to meet death. The secret of life is, surprisingly, best revealed to those who are not bound by their possessions. They are unaffected by worry and life's changing fortunes. They are individuals who do not live by adding things to life, but by weighing their lives by things they can do without.
"""

In [10]:
chat_message=[
    SystemMessage(content="You are expert with in expertise in summarizing speech"),
    HumanMessage(content=f"Please provide a short and concise summary od the following speech:\n Text:{speech}")
]

In [11]:
model.get_num_tokens(speech)

C:\gen_ai\GEN_AI\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\gen_ai\GEN_AI\venv\lib\site-packages\huggingface_hub\file_download.py:159: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\psavadi\.cache\huggingface\hub\models--gpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

198

In [12]:
# this is one way of creating the summary
model(chat_message).content

C:\gen_ai\GEN_AI\venv\lib\site-packages\langchain_core\_api\deprecation.py:139: LangChainDeprecationWarning: The method `BaseChatModel.__call__` was deprecated in langchain-core 0.1.7 and will be removed in 0.3.0. Use invoke instead.
  warn_deprecated(

'**Speech Summary:**\n\nLife is a precious gift from God, with each individual being unique and valuable. True success in life is measured not by longevity but by the positive impact we have on others through love and encouragement. Death is an inevitable part of life, but wise individuals embrace it with composure. The key to a fulfilling life is to live with humility, prioritizing actions over material possessions.'

In [13]:
# if we don't add .content it will give with the AI messgae
model(chat_message)

AIMessage(content='**Speech Summary:**\n\nLife is a precious gift from God. Its purpose is not merely to exist, but to make a meaningful impact through acts of love and encouragement. Death is an inevitable part of life, but true wisdom lies in embracing a life free from material possessions and worries. True wealth is measured by the positive influence one has on others.', response_metadata={'token_usage': {'completion_tokens': 71, 'prompt_tokens': 237, 'total_tokens': 308, 'completion_time': 0.082640073, 'prompt_time': 0.140280652, 'queue_time': None, 'total_time': 0.222920725}, 'model_name': 'Gemma-7b-It', 'system_fingerprint': 'fp_e3b292b95f', 'finish_reason': 'stop', 'logprobs': None}, id='run-097479c3-a287-43c8-8ad6-ac8f0b9ba0c3-0', usage_metadata={'input_tokens': 237, 'output_tokens': 71, 'total_tokens': 308})

In [ ]:
#summarized tokens
({'input_tokens': 237, 'output_tokens': 71, 'total_tokens': 308})

Prompt Template with Text Summarize 2nd way

In [15]:
from langchain.chains import LLMChain # LLMchain is to combine model|prompt
from langchain import PromptTemplate

In [17]:
# here we are giving 2 inputs speech and language
generictemplate="""
Write summary of following speech
speech:{speech}
Translate the prescribe summary to {language} 
"""
prompt=PromptTemplate(
    input_variables=['speech','language'],
    template=generictemplate
)
prompt

PromptTemplate(input_variables=['language', 'speech'], template='\nWrite summary of following speech\nspeech:{speech}\nTranslate the prescribe summary to {language} \n')

In [19]:
chat_prompt=prompt.format(speech=speech,language='Hindi')
# the below is the entire prompt

In [20]:
model.get_num_tokens(chat_prompt)

217

In [21]:
chain=LLMChain(llm=model,prompt=prompt)
summary=chain.run({"speech":speech,"language":'Hindi'})

C:\gen_ai\GEN_AI\venv\lib\site-packages\langchain_core\_api\deprecation.py:139: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 0.3.0. Use RunnableSequence, e.g., `prompt | llm` instead.
  warn_deprecated(
C:\gen_ai\GEN_AI\venv\lib\site-packages\langchain_core\_api\deprecation.py:139: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain 0.1.0 and will be removed in 0.3.0. Use invoke instead.
  warn_deprecated(

In [22]:
summary

'**Summary:**\n\nजीवन मूल्यपूर्ण है। यह एक देव की उपहार है। यह धरती पर किसी अन्य व्यक्ति के लिए एक विशेषता है। अस्तित्व, फिर भी एक अवसर है। यह अच्छा प्राप्त करने का अवसर है। इसलिए, आपकी उम्र कीliczने से अधिक महत्त्व यह है कि आपकी जीवन कैसे रहता है। और आप कैसे कई जीवनों को प्रेरणा और प्रेरणा से प्रभावित करते हैं।\n\nमृत्यु भी जीवन के साथ रहती है। हर कोई उससे मिलना है। उस व्यक्ति को बुद्ध और वरीय है, जो अपने वित्तीय पदों से बचे हुए है। वे जीवन में बदलते परिस्थितियों से प्रभावित नहीं हैं। वे वे लोग हैं जिनका जीवन उन चीजों से मापा जाता है जिनका वे उपयोग न करते हैं।'

In [24]:
model.get_num_tokens(summary)

847

StuffDocumentChain Text Summariztion

In [27]:
from langchain_community.document_loaders import PyPDFLoader
loader=PyPDFLoader('SQL_Notes_by_Apna_College.pdf')
docs=loader.load_and_split()
docs

[Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 0}, page_content='SQL\n(Notes\nby\nApna\nCollege)\nWhat\nis\nDatabase?\nDatabase\nis\na\ncollection\nof\ninterrelated\ndata.\nWhat\nis\nDBMS?\nDBMS\n(\nDatabase\nManagement\nSystem\n)\nis\nsoftware\nused\nto\ncreate,\nmanage,\nand\norganize\ndatabases.\nWhat\nis\nRDBMS?\n●\nRDBMS\n(Relational\nDatabase\nManagement\nSystem)\n-\nis\na\nDBMS\nbased\non\nthe\nconcept\nof\ntables\n(also\ncalled\nrelations).\n●\nData\nis\norganized\ninto\ntables\n(also\nknown\nas\nrelations)\nwith\nrows\n(records)\nand\ncolumns\n(attributes).\n●\nEg\n-\nMySQL,\nPostgreSQL,\nOracle\netc.\nWhat\nis\nSQL?\nSQL\nis\nStructured\nQuery\nLanguage\n-\nused\nto\nstore,\nmanipulate\nand\nretrieve\ndata\nfrom\nRDBMS.\n(It\nis\nnot\na\ndatabase,\nit\nis\na\nlanguage\nused\nto\ninteract\nwith\ndatabase)\nWe\nuse\nSQL\nfor\nCRUD\nOperations\n:\n●\nCREATE\n-\nTo\ncreate\ndatabases,\ntables,\ninsert\ntuples\nin\ntables\netc\n●\nREAD\n-\nTo\nread\ndata\npresent\nin\nthe\ndatabase.\n●\nUPDATE\n-\nModify\nalready\ninserted\ndata.\n●\nDELETE\n-\nDelete\ndatabase,\ntable\nor\nspecific\ndata\npoint/tuple/row\nor\nmultiple\nrows.\n*Note\n-\nSQL\nkeywords\nare\nNOT\ncase\nsensitive.\nEg:\nselect\nis\nthe\nsame\nas\nSELECT\nin\nSQL.\nSQL\nv/s\nMySQL\nSQL\nis\na\nlanguage\nused\nto\nperform\nCRUD\noperations\nin\nRelational\nDB,\nwhile\nMySQL\nis\na\nRDBMS\nthat\nuses\nSQL.'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 1}, page_content='SQL\nData\nTypes\nIn\nSQL,\ndata\ntypes\ndefine\nthe\nkind\nof\ndata\nthat\ncan\nbe\nstored\nin\na\ncolumn\nor\nvariable.\nTo\nSee\nall\ndata\ntypes\nof\nMYSQL,\nvisit\n:\nhttps://dev.mysql.com/doc/refman/8.0/en/data-types.html\nHere\nare\nthe\nfrequently\nused\nSQL\ndata\ntypes:\nDATATYPE\nDESCRIPTION\nUSAGE\nCHAR\nstring(0-255),\ncan\nstore\ncharacters\nof\nfixed\nlength\nCHAR(50)\nVARCHAR\nstring(0-255),\ncan\nstore\ncharacters\nup\nto\ngiven\nlength\nVARCHAR(50)\nBLOB\nstring(0-65535),\ncan\nstore\nbinary\nlarge\nobject\nBLOB(1000)\nINT\ninteger(\n-2,147,483,648\nto\n2,147,483,647\n)\nINT\nTINYINT\ninteger(-128\nto\n127)\nTINYINT\nBIGINT\ninteger(\n-9,223,372,036,854,775,808\nto \n9,223,372,036,854,775,807\n)\nBIGINT\nBIT\ncan\nstore\nx-bit\nvalues.\nx\ncan\nrange\nfrom\n1\nto\n64\nBIT(2)\nFLOAT\nDecimal\nnumber\n-\nwith\nprecision\nto\n23\ndigits\nFLOAT\nDOUBLE\nDecimal\nnumber\n-\nwith\n24\nto\n53\ndigits\nDOUBLE\nBOOLEAN\nBoolean\nvalues\n0\nor\n1\nBOOLEAN\nDATE\ndate\nin\nformat\nof\nYYYY-MM-DD\nranging\nfrom \n1000-01-01\nto\n9999-12-31\nDATE\nTIME\nHH:MM:SS\nTIME\nYEAR\nyear\nin\n4\ndigits\nformat\nranging\nfrom\n1901\nto\n2155\nYEAR\n*Note\n-\nCHAR\nis\nfor\nfixed\nlength\n&\nVARCHAR\nis\nfor\nvariable\nlength\nstrings.\nGenerally,\nVARCHAR\nis\nbetter\nas\nit\nonly\noccupies\nnecessary\nmemory\n&\nworks\nmore\nefficiently.\nWe\ncan\nalso\nuse\nUNSIGNED\nwith\ndatatypes\nwhen\nwe\nonly\nhave\npositive\nvalues\nto\nadd.\nEg\n-\nUNSIGNED\nINT\nTypes\nof\nSQL\nCommands:'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 2}, page_content='1.\nDQL\n(Data\nQuery\nLanguage)\n:\nUsed\nto\nretrieve\ndata\nfrom\ndatabases.\n(SELECT)\n2.\nDDL\n(Data\nDefinition\nLanguage)\n:\nUsed\nto\ncreate,\nalter,\nand\ndelete\ndatabase\nobjects\nlike\ntables,\nindexes,\netc.\n(CREATE,\nDROP,\nALTER,\nRENAME,\nTRUNCATE)\n3.\nDML\n(Data\nManipulation\nLanguage)\n:\nUsed\nto\nmodify\nthe\ndatabase.\n(INSERT,\nUPDATE,\nDELETE)\n4.\nDCL\n(Data\nControl\nLanguage)\n:\nUsed\nto\ngrant\n&\nrevoke\npermissions.\n(GRANT,\nREVOKE)\n5.\nTCL\n(Transaction\nControl\nLanguage)\n:\nUsed\nto\nmanage\ntransactions.\n(COMMIT,\nROLLBACK,\nSTART\nTRANSACTIONS,\nSAVEPOINT)\n1.\nData\nDefinition\nLanguage\n(DDL)\nData\nDefinition\nLanguage\n(DDL)\nis\na\nsubset\nof\nSQL\n(Structured\nQuery\nLanguage)\nresponsible\nfor\ndefining\nand\nmanaging\nthe\nstructure\nof\ndatabases\nand\ntheir\nobjects.\nDDL\ncommands\nenable\nyou\nto\ncreate,\nmodify,\nand\ndelete\ndatabase\nobjects\nlike\ntables,\nindexes,\nconstraints,\nand\nmore.\nKey\nDDL\nCommands\nare:\n●\nCREATE\nTABLE:\n○\nUsed\nto\ncreate\na\nnew\ntable\nin\nthe\ndatabase.\n○\nSpecifies\nthe\ntable\nname,\ncolumn\nnames,\ndata\ntypes,\nconstraints,\nand\nmore.\n○\nExample:\nCREATE\nTABLE\nemployees\n(id\nINT\nPRIMARY\nKEY,\nname\nVARCHAR(50),\nsalary\nDECIMAL(10,\n2));\n●\nALTER\nTABLE:\n○\nUsed\nto\nmodify\nthe\nstructure\nof\nan\nexisting\ntable.\n○\nYou\ncan\nadd,\nmodify,\nor\ndrop\ncolumns,\nconstraints,\nand\nmore.\n○\nExample:\nALTER\nTABLE\nemployees\nADD\nCOLUMN\nemail\nVARCHAR(100);\n●\nDROP\nTABLE:\n○\nUsed\nto\ndelete\nan\nexisting\ntable\nalong\nwith\nits\ndata\nand\nstructure.\n○\nExample:\nDROP\nTABLE\nemployees;'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 3}, page_content='●\nCREATE\nINDEX:\n○\nUsed\nto\ncreate\nan\nindex\non\none\nor\nmore\ncolumns\nin\na\ntable.\n○\nImproves\nquery\nperformance\nby\nenabling\nfaster\ndata\nretrieval.\n○\nExample:\nCREATE\nINDEX\nidx_employee_name\nON\nemployees\n(name);\n●\nDROP\nINDEX:\n○\nUsed\nto\nremove\nan\nexisting\nindex\nfrom\na\ntable.\n○\nExample:\nDROP\nINDEX\nidx_employee_name;\n●\nCREATE\nCONSTRAINT:\n○\nUsed\nto\ndefine\nconstraints\nthat\nensure\ndata\nintegrity.\n○\nConstraints\ninclude\nPRIMARY\nKEY,\nFOREIGN\nKEY,\nUNIQUE,\nNOT\nNULL,\nand\nCHECK.\n○\nExample:\nALTER\nTABLE\norders\nADD\nCONSTRAINT\nfk_customer\nFOREIGN\nKEY\n(customer_id)\nREFERENCES\ncustomers(id);\n●\nDROP\nCONSTRAINT:\n○\nUsed\nto\nremove\nan\nexisting\nconstraint\nfrom\na\ntable.\n○\nExample:\nALTER\nTABLE\norders\nDROP\nCONSTRAINT\nfk_customer;\n●\nTRUNCATE\nTABLE:\n○\nUsed\nto\ndelete\nthe\ndata\ninside\na\ntable,\nbut\nnot\nthe\ntable\nitself.\n○\nSyntax\n–\nTRUNCATE\nTABLE\ntable_name\n2.\nDATA\nQUER Y/RETRIEV AL\nLANGUAGE\n(DQL\nor\nDRL)\nDQL\n(Data\nQuery\nLanguage)\nis\na\nsubset\nof\nSQL\nfocused\non\nretrieving\ndata\nfrom\ndatabases.\nThe\nSELECT\nstatement\nis\nthe\nfoundation\nof\nDQL\nand\nallows\nus\nto\nextract\nspecific\ncolumns\nfrom\na\ntable.\n●\nSELECT:\nThe\nSELECT\nstatement\nis\nused\nto\nselect\ndata\nfrom\na\ndatabase.'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 4}, page_content="Syntax:\nSELECT\ncolumn1,\ncolumn2,\n...\nFROM\ntable_name;\nHere,\ncolumn1,\ncolumn2,\n...\nare\nthe\nfield\nnames\nof\nthe\ntable.\nIf\nyou\nwant\nto\nselect\nall\nthe\nfields\navailable\nin\nthe\ntable,\nuse\nthe\nfollowing\nsyntax:\nSELECT\n*\nFROM\ntable_name;\nEx:\nSELECT\nCustomerName,\nCity\nFROM\nCustomers;\n●\nWHERE:\nThe\nWHERE\nclause\nis\nused\nto\nfilter\nrecords.\nSyntax:\nSELECT\ncolumn1,\ncolumn2,\n...\nFROM\ntable_name\nWHERE\ncondition;\nEx:\nSELECT\n*\nFROM\nCustomers\nWHERE\nCountry='Mexico';\nOperators\nused\nin\nWHERE\nare:\n=\n:\nEqual\n>\n:\nGreater\nthan\n<\n:\nLess\nthan\n>=\n:\nGreater\nthan\nor\nequal\n<=\n:\nLess\nthan\nor\nequal\n<>\n:\nNot\nequal.\nNote:\nIn\nsome\nversions\nof\nSQL\nthis\noperator\nmay\nbe\nwritten\nas\n!=\n●\nAND,\nOR\nand\nNOT:\n-\nThe\nWHERE\nclause\ncan\nbe\ncombined\nwith\nAND,\nOR,\nand\nNOT\noperators.\n-\nThe\nAND\nand\nOR\noperators\nare\nused\nto\nfilter\nrecords\nbased\non\nmore\nthan\none\ncondition:\n-\nThe\nAND\noperator\ndisplays\na\nrecord\nif\nall\nthe\nconditions\nseparated\nby\nAND\nare\nTRUE.\n-\nThe\nOR\noperator\ndisplays\na\nrecord\nif\nany\nof\nthe\nconditions\nseparated\nby\nOR\nis\nTRUE.\n-\nThe\nNOT\noperator\ndisplays\na\nrecord\nif\nthe\ncondition(s)\nis\nNOT\nTRUE.\nSyntax:"),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 5}, page_content='SELECT\ncolumn1,\ncolumn2,\n...\nFROM\ntable_name\nWHERE\ncondition1\nAND\ncondition2\nAND\ncondition3\n...;\nSELECT\ncolumn1,\ncolumn2,\n...\nFROM\ntable_name\nWHERE\ncondition1\nOR\ncondition2\nOR\ncondition3\n...;\nSELECT\ncolumn1,\ncolumn2,\n...\nFROM\ntable_name\nWHERE\nNOT\ncondition;\nExample:\nSELECT\n*\nFROM\nCustomers\nWHERE\nCountry=’India’\nAND\nCity=’Japan’;\nSELECT\n*\nFROM\nCustomers\nWHERE\nCountry=’America’\nAND\n(City=’India’\nOR\nCity=’Korea’);\n●\nDISTINCT:\nRemoves\nduplicate\nrows\nfrom\nquery\nresults.\nSyntax:\nSELECT\nDISTINCT\ncolumn1,\ncolumn2\nFROM\ntable_name;\n●\nLIKE\n:\nThe\nLIKE\noperator\nis\nused\nin\na\nWHERE\nclause\nto\nsearch\nfor\na\nspecified\npattern\nin\na\ncolumn.\nThere\nare\ntwo\nwildcards\noften\nused\nin\nconjunction\nwith\nthe\nLIKE\noperator:\n-\nThe\npercent\nsign\n(%)\nrepresents\nzero,\none,\nor\nmultiple\ncharacters\n-\nThe\nunderscore\nsign\n(_)\nrepresents\none,\nsingle\ncharacter\nExample:\nSELECT\n*\nFROM\nemployees\nWHERE\nfirst_name\nLIKE\n\'J%\';\nWHERE\nCustomerName\nLIKE\n\'a%\'\n-\nFinds\nany\nvalues\nthat\nstart\nwith\n"a"\nWHERE\nCustomerName\nLIKE\n\'%a\'\n-\nFinds\nany\nvalues\nthat\nend\nwith\n"a"\nWHERE\nCustomerName\nLIKE\n\'%or%\'\n-\nFinds\nany\nvalues\nthat\nhave\n"or"\nin\nany\nposition\nWHERE\nCustomerName\nLIKE\n\'_r%\'\n-\nFinds\nany\nvalues\nthat\nhave\n"r"\nin\nthe\nsecond\nposition'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 6}, page_content='WHERE\nCustomerName\nLIKE\n\'a_%\'\n-\nFinds\nany\nvalues\nthat\nstart\nwith\n"a"\nand\nare\nat\nleast\n2\ncharacters\nin\nlength\nWHERE\nCustomerName\nLIKE\n\'a__%\'\n-\nFinds\nany\nvalues\nthat\nstart\nwith\n"a"\nand\nare\nat\nleast\n3\ncharacters\nin\nlength\nWHERE\nContactName\nLIKE\n\'a%o\'\n-\nFinds\nany\nvalues\nthat\nstart\nwith\n"a"\nand\nends\nwith\n"o"\n●\nIN:\nFilters\nresults\nbased\non\na\nlist\nof\nvalues\nin\nthe\nWHERE\nclause.\nExample:\nSELECT\n*\nFROM\nproducts\nWHERE\ncategory_id\nIN\n(1,\n2,\n3);\n●\nBETWEEN\n:\nFilters\nresults\nwithin\na\nspecified\nrange\nin\nthe\nWHERE\nclause.\nExample:\nSELECT\n*\nFROM\norders\nWHERE\norder_date\nBETWEEN\n\'2023-01-01\'\nAND\n\'2023-06-30\';\n●\nIS\nNULL\n:\nChecks\nfor\nNULL\nvalues\nin\nthe\nWHERE\nclause.\nExample:\nSELECT\n*\nFROM\ncustomers\nWHERE\nemail\nIS\nNULL;\n●\nAS\n:\nRenames\ncolumns\nor\nexpressions\nin\nquery\nresults.\nExample:\nSELECT\nfirst_name\nAS\n"First\nName",\nlast_name\nAS\n"Last\nName"\nFROM\nemployees;\n●\nORDER\nBY\nThe\nORDER\nBY\nclause\nallows\nyou\nto\nsort\nthe\nresult\nset\nof\na\nquery\nbased\non\none\nor\nmore\ncolumns.\nBasic\nSyntax:\n-\nThe\nORDER\nBY\nclause\nis\nused\nafter\nthe\nSELECT\nstatement\nto\nsort\nquery\nresults.'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 7}, page_content="-\nSyntax:\nSELECT\ncolumn1,\ncolumn2\nFROM\ntable_name\nORDER\nBY\ncolumn1\n[ASC|DESC];\nAscending\nand\nDescending\nOrder:\n-\nBy\ndefault,\nthe\nORDER\nBY\nclause\nsorts\nin\nascending\norder\n(smallest\nto\nlargest).\n-\nYou\ncan\nexplicitly\nspecify\ndescending\norder\nusing\nthe\nDESC\nkeyword.\n-\nExample:\nSELECT\nproduct_name,\nprice\nFROM\nproducts\nORDER\nBY\nprice\nDESC;\nSorting\nby\nMultiple\nColumns:\n-\nYou\ncan\nsort\nby\nmultiple\ncolumns\nby\nlisting\nthem\nsequentially\nin\nthe\nORDER\nBY\nclause.\n-\nRows\nare\nfirst\nsorted\nbased\non\nthe\nfirst\ncolumn,\nand\nfor\nrows\nwith\nequal\nvalues,\nsubsequent\ncolumns\nare\nused\nfor\nfurther\nsorting.\n-\nExample:\nSELECT\nfirst_name,\nlast_name\nFROM\nemployees\nORDER\nBY\nlast_name,\nfirst_name;\nSorting\nby\nExpressions:\n-\nIt's\npossible\nto\nsort\nby\ncalculated\nexpressions,\nnot\njust\ncolumn\nvalues.\n-\nExample:\nSELECT\nproduct_name,\nprice,\nprice\n*\n1.1\nAS\ndiscounted_price\nFROM\nproducts\nORDER\nBY\ndiscounted_price;\nSorting\nNULL\nValues:\n-\nBy\ndefault,\nNULL\nvalues\nare\nconsidered\nthe\nsmallest\nin\nascending\norder\nand\nthe\nlargest\nin\ndescending\norder.\n-\nYou\ncan\ncontrol\nthe\nsorting\nbehaviour\nof\nNULL\nvalues\nusing\nthe\nNULLS\nFIRST\nor\nNULLS\nLAST\noptions.\n-\nExample:\nSELECT\ncolumn_name\nFROM\ntable_name\nORDER\nBY\ncolumn_name\nNULLS\nLAST;\nSorting\nby\nPosition:\n-\nInstead\nof\nspecifying\ncolumn\nnames,\nyou\ncan\nsort\nby\ncolumn\npositions\nin\nthe\nORDER\nBY\nclause.\n-\nExample:\nSELECT\nproduct_name,\nprice\nFROM\nproducts\nORDER\nBY\n2\nDESC,\n1\nASC;\n●\nGROUP\nBY\nThe\nGROUP\nBY\nclause\nin\nSQL\nis\nused\nto\ngroup\nrows\nfrom\na\ntable\nbased\non\none\nor\nmore\ncolumns.\nSyntax:"),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 8}, page_content="-\nThe\nGROUP\nBY\nclause\nfollows\nthe\nSELECT\nstatement\nand\nis\nused\nto\ngroup\nrows\nbased\non\nspecified\ncolumns.\n-\nSyntax:\nSELECT\ncolumn1,\naggregate_function(column2)\nFROM\ntable_name\nGROUP\nBY\ncolumn1;\n-\nAggregation\nFunctions:\n○\nAggregation\nfunctions\n(e.g.,\nCOUNT,\nSUM,\nAVG,\nMAX,\nMIN)\nare\noften\nused\nwith\nGROUP\nBY\nto\ncalculate\nvalues\nfor\neach\ngroup.\n○\nExample:\nSELECT\ndepartment,\nAVG(salary)\nFROM\nemployees\nGROUP\nBY\ndepartment;\n-\nGrouping\nby\nMultiple\nColumns:\n○\nYou\ncan\ngroup\nby\nmultiple\ncolumns\nby\nlisting\nthem\nin\nthe\nGROUP\nBY\nclause.\n○\nThis\ncreates\na\nhierarchical\ngrouping\nbased\non\nthe\nspecified\ncolumns.\n○\nExample:\nSELECT\ndepartment,\ngender,\nAVG(salary)\nFROM\nemployees\nGROUP\nBY\ndepartment,\ngender;\n-\nHAVING\nClause:\n○\nThe\nHAVING\nclause\nis\nused\nwith\nGROUP\nBY\nto\nfilter\ngroups\nbased\non\naggregate\nfunction\nresults.\n○\nIt's\nsimilar\nto\nthe\nWHERE\nclause\nbut\noperates\non\ngrouped\ndata.\n○\nExample:\nSELECT\ndepartment,\nAVG(salary)\nFROM\nemployees\nGROUP\nBY\ndepartment\nHAVING\nAVG(salary)\n>\n50000;\n-\nCombining\nGROUP\nBY\nand\nORDER\nBY:\n○\nYou\ncan\nuse\nboth\nGROUP\nBY\nand\nORDER\nBY\nin\nthe\nsame\nquery\nto\ncontrol\nthe\norder\nof\ngrouped\nresults.\n○\nExample:\nSELECT\ndepartment,\nCOUNT(*)\nFROM\nemployees\nGROUP\nBY\ndepartment\nORDER\nBY\nCOUNT(*)\nDESC;\n●\nAGGREGATE\nFUNCTIONS\nThese\nare\nused\nto\nperform\ncalculations\non\ngroups\nof\nrows\nor\nentire\nresult\nsets.\nThey\nprovide\ninsights\ninto\ndata\nby\nsummarising\nand\nprocessing\ninformation.\nCommon\nAggregate\nFunctions:\n-\nCOUNT():\nCounts\nthe\nnumber\nof\nrows\nin\na\ngroup\nor\nresult\nset.\n-\nSUM():\nCalculates\nthe\nsum\nof\nnumeric\nvalues\nin\na\ngroup\nor\nresult\nset.\n-\nAVG():"),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 9}, page_content="Computes\nthe\naverage\nof\nnumeric\nvalues\nin\na\ngroup\nor\nresult\nset.\n-\nMAX():\nFinds\nthe\nmaximum\nvalue\nin\na\ngroup\nor\nresult\nset.\n-\nMIN():\nRetrieves\nthe\nminimum\nvalue\nin\na\ngroup\nor\nresult\nset.\n3.\nDATA\nMANIPULA TION\nLANGUAGE\nData\nManipulation\nLanguage\n(DML)\nin\nSQL\nencompasses\ncommands\nthat\nmanipulate\ndata\nwithin\na\ndatabase.\nDML\nallows\nyou\nto\ninsert,\nupdate,\nand\ndelete\nrecords,\nensuring\nthe\naccuracy\nand\ncurrency\nof\nyour\ndata.\n●\nINSERT:\n-\nThe\nINSERT\nstatement\nadds\nnew\nrecords\nto\na\ntable.\n-\nSyntax:\nINSERT\nINTO\ntable_name\n(column1,\ncolumn2,\n...)\nVALUES\n(value1,\nvalue2,\n...);\n-\nExample:\nINSERT\nINTO\nemployees\n(first_name,\nlast_name,\nsalary)\nVALUES\n('John',\n'Doe',\n50000);\n●\nUPDATE\n:\n-\nThe\nUPDATE\nstatement\nmodifies\nexisting\nrecords\nin\na\ntable.\n-\nSyntax:\nUPDATE\ntable_name\nSET\ncolumn1\n=\nvalue1,\ncolumn2\n=\nvalue2,\n...\nWHERE\ncondition;\n-\nExample:\nUPDATE\nemployees\nSET\nsalary\n=\n55000\nWHERE\nfirst_name\n=\n'John';\n●\nDELETE\n:\n-\nThe\nDELETE\nstatement\nremoves\nrecords\nfrom\na\ntable.\n-\nSyntax:\nDELETE\nFROM\ntable_name\nWHERE\ncondition;\n-\nExample:\nDELETE\nFROM\nemployees\nWHERE\nlast_name\n=\n'Doe';\n4.\nData\nControl\nLanguage\n(DCL)"),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 10}, page_content='Data\nControl\nLanguage\nfocuses\non\nthe\nmanagement\nof\naccess\nrights,\npermissions,\nand\nsecurity-related\naspects\nof\na\ndatabase\nsystem.\nDCL\ncommands\nare\nused\nto\ncontrol\nwho\ncan\naccess\nthe\ndata,\nmodify\nthe\ndata,\nor\nperform\nadministrative\ntasks\nwithin\na\ndatabase.\nDCL\nis\nan\nimportant\naspect\nof\ndatabase\nsecurity,\nensuring\nthat\ndata\nremains\nprotected\nand\nonly\nauthorised\nusers\nhave\nthe\nnecessary\nprivileges.\nThere\nare\ntwo\nmain\nDCL\ncommands\nin\nSQL:\nGRANT\nand\nREVOKE.\n1.\nGRANT:\nThe\nGRANT\ncommand\nis\nused\nto\nprovide\nspecific\nprivileges\nor\npermissions\nto\nusers\nor\nroles.\nPrivileges\ncan\ninclude\nthe\nability\nto\nperform\nvarious\nactions\non\ntables,\nviews,\nprocedures,\nand\nother\ndatabase\nobjects.\nSyntax:\nGRANT\nprivilege_type\nON\nobject_name\nTO\nuser_or_role;\nIn\nthis\nsyntax:\n●\nprivilege_type\nrefers\nto\nthe\nspecific\nprivilege\nor\npermission\nbeing\ngranted\n(e.g.,\nSELECT,\nINSERT,\nUPDATE,\nDELETE).\n●\nobject_name\nis\nthe\nname\nof\nthe\ndatabase\nobject\n(e.g.,\ntable,\nview)\nto\nwhich\nthe\nprivilege\nis\nbeing\ngranted.\n●\nuser_or_role\nis\nthe\nname\nof\nthe\nuser\nor\nrole\nthat\nis\nbeing\ngranted\nthe\nprivilege.\nExample:\nGranting\nSELECT\nprivilege\non\na\ntable\nnamed\n"Employees"\nto\na\nuser\nnamed\n"Analyst":\nGRANT\nSELECT\nON\nEmployees\nTO\nAnalyst;\n2.\nREVOKE:\nThe\nREVOKE\ncommand\nis\nused\nto\nremove\nor\nrevoke\nspecific\nprivileges\nor\npermissions\nthat\nhave\nbeen\npreviously\ngranted\nto\nusers\nor\nroles.\nSyntax:\nREVOKE\nprivilege_type\nON\nobject_name'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 11}, page_content='FROM\nuser_or_role;\nIn\nthis\nsyntax:\n●\nprivilege_type\nis\nthe\nprivilege\nor\npermission\nbeing\nrevoked.\n●\nobject_name\nis\nthe\nname\nof\nthe\ndatabase\nobject\nfrom\nwhich\nthe\nprivilege\nis\nbeing\nrevoked.\n●\nuser_or_role\nis\nthe\nname\nof\nthe\nuser\nor\nrole\nfrom\nwhich\nthe\nprivilege\nis\nbeing\nrevoked.\nExample:\nRevoking\nthe\nSELECT\nprivilege\non\nthe\n"Employees"\ntable\nfrom\nthe\n"Analyst"\nuser:\nREVOKE\nSELECT\nON\nEmployees\nFROM\nAnalyst;\nDCL\nand\nDatabase\nSecurity:\nDCL\nplays\na\ncrucial\nrole\nin\nensuring\nthe\nsecurity\nand\nintegrity\nof\na\ndatabase\nsystem.\nBy\ncontrolling\naccess\nand\npermissions,\nDCL\nhelps\nprevent\nunauthorised\nusers\nfrom\ntampering\nwith\nor\naccessing\nsensitive\ndata.\nProper\nuse\nof\nGRANT\nand\nREVOKE\ncommands\nensures\nthat\nonly\nusers\nwho\nrequire\nspecific\nprivileges\ncan\nperform\ncertain\nactions\non\ndatabase\nobjects.\n5.\nTransaction\nControl\nLanguage\n(TCL)\nTransaction\nControl\nLanguage\n(TCL)\ndeals\nwith\nthe\nmanagement\nof\ntransactions\nwithin\na\ndatabase.\nTCL\ncommands\nare\nused\nto\ncontrol\nthe\ninitiation,\nexecution,\nand\ntermination\nof\ntransactions,\nwhich\nare\nsequences\nof\none\nor\nmore\nSQL\nstatements\nthat\nare\nexecuted\nas\na\nsingle\nunit\nof\nwork.\nTransactions\nensure\ndata\nconsistency,\nintegrity,\nand\nreliability\nin\na\ndatabase\nby\ngrouping\nrelated\noperations\ntogether\nand\neither\ncommitting\nor\nrolling\nback\nchanges\nbased\non\nthe\nsuccess\nor\nfailure\nof\nthose\noperations.\nThere\nare\nthree\nmain\nTCL\ncommands\nin\nSQL:\nCOMMIT,\nROLLBACK,\nand\nSAVEPOINT.\n1.\nCOMMIT:\nThe\nCOMMIT\ncommand\nis\nused\nto\npermanently\nsave\nthe\nchanges\nmade\nduring\na\ntransaction.'),

In [28]:
template=""" Write a concise and short summary of following speech,
speech:{text}
"""
prompt=PromptTemplate(inpt_variable=['text'],template=template)

In [29]:
from langchain.chains.summarize import load_summarize_chain
chain=load_summarize_chain(model,chain_type='stuff',prompt=prompt,verbose=True)
# here when we specfic chain_type= stuff firstly it will combine the docs then passed to prompt template and then it is passed to llm model and finally
# we will get summary of text

In [32]:
output_summary=chain.run(docs)
output_summary

> Entering new StuffDocumentsChain chain...


> Entering new LLMChain chain...
Prompt after formatting:
 Write a concise and short summary of following speech,
speech:SQL
(Notes
by
Apna
College)
What
is
Database?
Database
is
a
collection
of
interrelated
data.
What
is
DBMS?
DBMS
(
Database
Management
System
)
is
software
used
to
create,
manage,
and
organize
databases.
What
is
RDBMS?
●
RDBMS
(Relational
Database
Management
System)
-
is
a
DBMS
based
on
the
concept
of
tables
(also
called
relations).
●
Data
is
organized
into
tables
(also
known
as
relations)
with
rows
(records)
and
columns
(attributes).
●
Eg
-
MySQL,
PostgreSQL,
Oracle
etc.
What
is
SQL?
SQL
is
Structured
Query
Language
-
used
to
store,
manipulate
and
retrieve
data
from
RDBMS.
(It
is
not
a
database,
it
is
a
language
used
to
interact
with
database)
We
use
SQL
for
CRUD
Operations
:
●
CREATE
-
To
create
databases,
tables,
insert
tuples
in
tables
etc
●
READ
-
To
read
data
present
in
the
database.
●
UPDATE
-
Modify
already
inserted
data.
●
DELETE
-
Delete
database,
table
or
specific
data
point/tuple/row
or
multiple
rows.
*Note
-
SQL
keywords
are
NOT
case
sensitive.
Eg:
select
is
the
same
as
SELECT
in
SQL.
SQL
v/s
MySQL
SQL
is
a
language
used
to
perform
CRUD
operations
in
Relational
DB,
while
MySQL
is
a
RDBMS
that
uses
SQL.

SQL
Data
Types
In
SQL,
data
types
define
the
kind
of
data
that
can
be
stored
in
a
column
or
variable.
To
See
all
data
types
of
MYSQL,
visit
:
https://dev.mysql.com/doc/refman/8.0/en/data-types.html
Here
are
the
frequently
used
SQL
data
types:
DATATYPE
DESCRIPTION
USAGE
CHAR
string(0-255),
can
store
characters
of
fixed
length
CHAR(50)
VARCHAR
string(0-255),
can
store
characters
up
to
given
length
VARCHAR(50)
BLOB
string(0-65535),
can
store
binary
large
object
BLOB(1000)
INT
integer(
-2,147,483,648
to
2,147,483,647
)
INT
TINYINT
integer(-128
to
127)
TINYINT
BIGINT
integer(
-9,223,372,036,854,775,808
to
9,223,372,036,854,775,807
)
BIGINT
BIT
can
store
x-bit
values.
x
can
range
from
1
to
64
BIT(2)
FLOAT
Decimal
number
-
with
precision
to
23
digits
FLOAT
DOUBLE
Decimal
number
-
with
24
to
53
digits
DOUBLE
BOOLEAN
Boolean
values
0
or
1
BOOLEAN
DATE
date
in
format
of
YYYY-MM-DD
ranging
from
1000-01-01
to
9999-12-31
DATE
TIME
HH:MM:SS
TIME
YEAR
year
in
4
digits
format
ranging
from
1901
to
2155
YEAR
*Note
-
CHAR
is
for
fixed
length
&
VARCHAR
is
for
variable
length
strings.
Generally,
VARCHAR
is
better
as
it
only
occupies
necessary
memory
&
works
more
efficiently.
We
can
also
use
UNSIGNED
with
datatypes
when
we
only
have
positive
values
to
add.
Eg
-
UNSIGNED
INT
Types
of
SQL
Commands:

1.
DQL
(Data
Query
Language)
:
Used
to
retrieve
data
from
databases.
(SELECT)
2.
DDL
(Data
Definition
Language)
:
Used
to
create,
alter,
and
delete
database
objects
like
tables,
indexes,
etc.
(CREATE,
DROP,
ALTER,
RENAME,
TRUNCATE)
3.
DML
(Data
Manipulation
Language)
:
Used
to
modify
the
database.
(INSERT,
UPDATE,
DELETE)
4.
DCL
(Data
Control
Language)
:
Used
to
grant
&
revoke
permissions.
(GRANT,
REVOKE)
5.
TCL
(Transaction
Control
Language)
:
Used
to
manage
transactions.
(COMMIT,
ROLLBACK,
START
TRANSACTIONS,
SAVEPOINT)
1.
Data
Definition
Language
(DDL)
Data
Definition
Language
(DDL)
is
a
subset
of
SQL
(Structured
Query
Language)
responsible
for
defining
and
managing
the
structure
of
databases
and
their
objects.
DDL
commands
enable
you
to
create,
modify,
and
delete
database
objects
like
tables,
indexes,
constraints,
and
more.
Key
DDL
Commands
are:
●
CREATE
TABLE:
○
Used
to
create
a
new
table
in
the
database.
○
Specifies
the
table
name,
column
names,
data
types,
constraints,
and
more.
○
Example:
CREATE
TABLE
employees
(id
INT
PRIMARY
KEY,
name
VARCHAR(50),
salary
DECIMAL(10,
2));
●
ALTER
TABLE:
○
Used
to
modify
the
structure
of
an
existing
table.
○
You
can
add,
modify,
or
drop
columns,
constraints,
and
more.
○
Example:
ALTER
TABLE
employees
ADD
COLUMN
email
VARCHAR(100);
●
DROP
TABLE:
○
Used
to
delete
an
existing
table
along
with
its
data
and
structure.
○
Example:
DROP
TABLE
employees;

●
CREATE
INDEX:
○
Used
to
create
an
index
on
one
or
more
columns
in
a
table.
○
Improves
query
performance
by
enabling
faster
data
retrieval.
○
Example:
CREATE
INDEX
idx_employee_name
ON
employees
(name);
●
DROP
INDEX:
○
Used
to
remove
an
existing
index
from
a
table.
○
Example:
DROP
INDEX
idx_employee_name;
●
CREATE
CONSTRAINT:
○
Used
to
define
constraints
that
ensure
data
integrity.
○
Constraints
include
PRIMARY
KEY,
FOREIGN
KEY,
UNIQUE,
NOT
NULL,
and
CHECK.
○
Example:
ALTER
TABLE
orders
ADD
CONSTRAINT
fk_customer
FOREIGN
KEY
(customer_id)
REFERENCES
customers(id);
●
DROP
CONSTRAINT:
○
Used
to
remove
an
existing
constraint
from
a
table.
○
Example:
ALTER
TABLE
orders
DROP
CONSTRAINT
fk_customer;
●
TRUNCATE
TABLE:
○
Used
to
delete
the
data
inside
a
table,
but
not
the
table
itself.
○
Syntax
–
TRUNCATE
TABLE
table_name
2.
DATA
QUER Y/RETRIEV AL
LANGUAGE
(DQL
or
DRL)
DQL
(Data
Query
Language)
is
a
subset
of
SQL
focused
on
retrieving
data
from
databases.
The
SELECT
statement
is
the
foundation
of
DQL
and
allows
us
to
extract
specific
columns
from
a
table.
●
SELECT:
The
SELECT
statement
is
used
to
select
data
from
a
database.

Syntax:
SELECT
column1,
column2,
...
FROM
table_name;
Here,
column1,
column2,
...
are
the
field
names
of
the
table.
If
you
want
to
select
all
the
fields
available
in
the
table,
use
the
following
syntax:
SELECT
*
FROM
table_name;
Ex:
SELECT
CustomerName,
City
FROM
Customers;
●
WHERE:
The
WHERE
clause
is
used
to
filter
records.
Syntax:
SELECT
column1,
column2,
...
FROM
table_name
WHERE
condition;
Ex:
SELECT
*
FROM
Customers
WHERE
Country='Mexico';
Operators
used
in
WHERE
are:
=
:
Equal
>
:
Greater
than
<
:
Less
than
>=
:
Greater
than
or
equal
<=
:
Less
than
or
equal
<>
:
Not
equal.
Note:
In
some
versions
of
SQL
this
operator
may
be
written
as
!=
●
AND,
OR
and
NOT:
-
The
WHERE
clause
can
be
combined
with
AND,
OR,
and
NOT
operators.
-
The
AND
and
OR
operators
are
used
to
filter
records
based
on
more
than
one
condition:
-
The
AND
operator
displays
a
record
if
all
the
conditions
separated
by
AND
are
TRUE.
-
The
OR
operator
displays
a
record
if
any
of
the
conditions
separated
by
OR
is
TRUE.
-
The
NOT
operator
displays
a
record
if
the
condition(s)
is
NOT
TRUE.
Syntax:

SELECT
column1,
column2,
...
FROM
table_name
WHERE
condition1
AND
condition2
AND
condition3
...;
SELECT
column1,
column2,
...
FROM
table_name
WHERE
condition1
OR
condition2
OR
condition3
...;
SELECT
column1,
column2,
...
FROM
table_name
WHERE
NOT
condition;
Example:
SELECT
*
FROM
Customers
WHERE
Country=’India’
AND
City=’Japan’;
SELECT
*
FROM
Customers
WHERE
Country=’America’
AND
(City=’India’
OR
City=’Korea’);
●
DISTINCT:
Removes
duplicate
rows
from
query
results.
Syntax:
SELECT
DISTINCT
column1,
column2
FROM
table_name;
●
LIKE
:
The
LIKE
operator
is
used
in
a
WHERE
clause
to
search
for
a
specified
pattern
in
a
column.
There
are
two
wildcards
often
used
in
conjunction
with
the
LIKE
operator:
-
The
percent
sign
(%)
represents
zero,
one,
or
multiple
characters
-
The
underscore
sign
(_)
represents
one,
single
character
Example:
SELECT
*
FROM
employees
WHERE
first_name
LIKE
'J%';
WHERE
CustomerName
LIKE
'a%'
-
Finds
any
values
that
start
with
"a"
WHERE
CustomerName
LIKE
'%a'
-
Finds
any
values
that
end
with
"a"
WHERE
CustomerName
LIKE
'%or%'
-
Finds
any
values
that
have
"or"
in
any
position
WHERE
CustomerName
LIKE
'_r%'
-
Finds
any
values
that
have
"r"
in
the
second
position

WHERE
CustomerName
LIKE
'a_%'
-
Finds
any
values
that
start
with
"a"
and
are
at
least
2
characters
in
length
WHERE
CustomerName
LIKE
'a__%'
-
Finds
any
values
that
start
with
"a"
and
are
at
least
3
characters
in
length
WHERE
ContactName
LIKE
'a%o'
-
Finds
any
values
that
start
with
"a"
and
ends
with
"o"
●
IN:
Filters
results
based
on
a
list
of
values
in
the
WHERE
clause.
Example:
SELECT
*
FROM
products
WHERE
category_id
IN
(1,
2,
3);
●
BETWEEN
:
Filters
results
within
a
specified
range
in
the
WHERE
clause.
Example:
SELECT
*
FROM
orders
WHERE
order_date
BETWEEN
'2023-01-01'
AND
'2023-06-30';
●
IS
NULL
:
Checks
for
NULL
values
in
the
WHERE
clause.
Example:
SELECT
*
FROM
customers
WHERE
email
IS
NULL;
●
AS
:
Renames
columns
or
expressions
in
query
results.
Example:
SELECT
first_name
AS
"First
Name",
last_name
AS
"Last
Name"
FROM
employees;
●
ORDER
BY
The
ORDER
BY
clause
allows
you
to
sort
the
result
set
of
a
query
based
on
one
or
more
columns.
Basic
Syntax:
-
The
ORDER
BY
clause
is
used
after
the
SELECT
statement
to
sort
query
results.

-
Syntax:
SELECT
column1,
column2
FROM
table_name
ORDER
BY
column1
[ASC|DESC];
Ascending
and
Descending
Order:
-
By
default,
the
ORDER
BY
clause
sorts
in
ascending
order
(smallest
to
largest).
-
You
can
explicitly
specify
descending
order
using
the
DESC
keyword.
-
Example:
SELECT
product_name,
price
FROM
products
ORDER
BY
price
DESC;
Sorting
by
Multiple
Columns:
-
You
can
sort
by
multiple
columns
by
listing
them
sequentially
in
the
ORDER
BY
clause.
-
Rows
are
first
sorted
based
on
the
first
column,
and
for
rows
with
equal
values,
subsequent
columns
are
used
for
further
sorting.
-
Example:
SELECT
first_name,
last_name
FROM
employees
ORDER
BY
last_name,
first_name;
Sorting
by
Expressions:
-
It's
possible
to
sort
by
calculated
expressions,
not
just
column
values.
-
Example:
SELECT
product_name,
price,
price
*
1.1
AS
discounted_price
FROM
products
ORDER
BY
discounted_price;
Sorting
NULL
Values:
-
By
default,
NULL
values
are
considered
the
smallest
in
ascending
order
and
the
largest
in
descending
order.
-
You
can
control
the
sorting
behaviour
of
NULL
values
using
the
NULLS
FIRST
or
NULLS
LAST
options.
-
Example:
SELECT
column_name
FROM
table_name
ORDER
BY
column_name
NULLS
LAST;
Sorting
by
Position:
-
Instead
of
specifying
column
names,
you
can
sort
by
column
positions
in
the
ORDER
BY
clause.
-
Example:
SELECT
product_name,
price
FROM
products
ORDER
BY
2
DESC,
1
ASC;
●
GROUP
BY
The
GROUP
BY
clause
in
SQL
is
used
to
group
rows
from
a
table
based
on
one
or
more
columns.
Syntax:

-
The
GROUP
BY
clause
follows
the
SELECT
statement
and
is
used
to
group
rows
based
on
specified
columns.
-
Syntax:
SELECT
column1,
aggregate_function(column2)
FROM
table_name
GROUP
BY
column1;
-
Aggregation
Functions:
○
Aggregation
functions
(e.g.,
COUNT,
SUM,
AVG,
MAX,
MIN)
are
often
used
with
GROUP
BY
to
calculate
values
for
each
group.
○
Example:
SELECT
department,
AVG(salary)
FROM
employees
GROUP
BY
department;
-
Grouping
by
Multiple
Columns:
○
You
can
group
by
multiple
columns
by
listing
them
in
the
GROUP
BY
clause.
○
This
creates
a
hierarchical
grouping
based
on
the
specified
columns.
○
Example:
SELECT
department,
gender,
AVG(salary)
FROM
employees
GROUP
BY
department,
gender;
-
HAVING
Clause:
○
The
HAVING
clause
is
used
with
GROUP
BY
to
filter
groups
based
on
aggregate
function
results.
○
It's
similar
to
the
WHERE
clause
but
operates
on
grouped
data.
○
Example:
SELECT
department,
AVG(salary)
FROM
employees
GROUP
BY
department
HAVING
AVG(salary)
>
50000;
-
Combining
GROUP
BY
and
ORDER
BY:
○
You
can
use
both
GROUP
BY
and
ORDER
BY
in
the
same
query
to
control
the
order
of
grouped
results.
○
Example:
SELECT
department,
COUNT(*)
FROM
employees
GROUP
BY
department
ORDER
BY
COUNT(*)
DESC;
●
AGGREGATE
FUNCTIONS
These
are
used
to
perform
calculations
on
groups
of
rows
or
entire
result
sets.
They
provide
insights
into
data
by
summarising
and
processing
information.
Common
Aggregate
Functions:
-
COUNT():
Counts
the
number
of
rows
in
a
group
or
result
set.
-
SUM():
Calculates
the
sum
of
numeric
values
in
a
group
or
result
set.
-
AVG():

Computes
the
average
of
numeric
values
in
a
group
or
result
set.
-
MAX():
Finds
the
maximum
value
in
a
group
or
result
set.
-
MIN():
Retrieves
the
minimum
value
in
a
group
or
result
set.
3.
DATA
MANIPULA TION
LANGUAGE
Data
Manipulation
Language
(DML)
in
SQL
encompasses
commands
that
manipulate
data
within
a
database.
DML
allows
you
to
insert,
update,
and
delete
records,
ensuring
the
accuracy
and
currency
of
your
data.
●
INSERT:
-
The
INSERT
statement
adds
new
records
to
a
table.
-
Syntax:
INSERT
INTO
table_name
(column1,
column2,
...)
VALUES
(value1,
value2,
...);
-
Example:
INSERT
INTO
employees
(first_name,
last_name,
salary)
VALUES
('John',
'Doe',
50000);
●
UPDATE
:
-
The
UPDATE
statement
modifies
existing
records
in
a
table.
-
Syntax:
UPDATE
table_name
SET
column1
=
value1,
column2
=
value2,
...
WHERE
condition;
-
Example:
UPDATE
employees
SET
salary
=
55000
WHERE
first_name
=
'John';
●
DELETE
:
-
The
DELETE
statement
removes
records
from
a
table.
-
Syntax:
DELETE
FROM
table_name
WHERE
condition;
-
Example:
DELETE
FROM
employees
WHERE
last_name
=
'Doe';
4.
Data
Control
Language
(DCL)

Data
Control
Language
focuses
on
the
management
of
access
rights,
permissions,
and
security-related
aspects
of
a
database
system.
DCL
commands
are
used
to
control
who
can
access
the
data,
modify
the
data,
or
perform
administrative
tasks
within
a
database.
DCL
is
an
important
aspect
of
database
security,
ensuring
that
data
remains
protected
and
only
authorised
users
have
the
necessary
privileges.
There
are
two
main
DCL
commands
in
SQL:
GRANT
and
REVOKE.
1.
GRANT:
The
GRANT
command
is
used
to
provide
specific
privileges
or
permissions
to
users
or
roles.
Privileges
can
include
the
ability
to
perform
various
actions
on
tables,
views,
procedures,
and
other
database
objects.
Syntax:
GRANT
privilege_type
ON
object_name
TO
user_or_role;
In
this
syntax:
●
privilege_type
refers
to
the
specific
privilege
or
permission
being
granted
(e.g.,
SELECT,
INSERT,
UPDATE,
DELETE).
●
object_name
is
the
name
of
the
database
object
(e.g.,
table,
view)
to
which
the
privilege
is
being
granted.
●
user_or_role
is
the
name
of
the
user
or
role
that
is
being
granted
the
privilege.
Example:
Granting
SELECT
privilege
on
a
table
named
"Employees"
to
a
user
named
"Analyst":
GRANT
SELECT
ON
Employees
TO
Analyst;
2.
REVOKE:
The
REVOKE
command
is
used
to
remove
or
revoke
specific
privileges
or
permissions
that
have
been
previously
granted
to
users
or
roles.
Syntax:
REVOKE
privilege_type
ON
object_name

FROM
user_or_role;
In
this
syntax:
●
privilege_type
is
the
privilege
or
permission
being
revoked.
●
object_name
is
the
name
of
the
database
object
from
which
the
privilege
is
being
revoked.
●
user_or_role
is
the
name
of
the
user
or
role
from
which
the
privilege
is
being
revoked.
Example:
Revoking
the
SELECT
privilege
on
the
"Employees"
table
from
the
"Analyst"
user:
REVOKE
SELECT
ON
Employees
FROM
Analyst;
DCL
and
Database
Security:
DCL
plays
a
crucial
role
in
ensuring
the
security
and
integrity
of
a
database
system.
By
controlling
access
and
permissions,
DCL
helps
prevent
unauthorised
users
from
tampering
with
or
accessing
sensitive
data.
Proper
use
of
GRANT
and
REVOKE
commands
ensures
that
only
users
who
require
specific
privileges
can
perform
certain
actions
on
database
objects.
5.
Transaction
Control
Language
(TCL)
Transaction
Control
Language
(TCL)
deals
with
the
management
of
transactions
within
a
database.
TCL
commands
are
used
to
control
the
initiation,
execution,
and
termination
of
transactions,
which
are
sequences
of
one
or
more
SQL
statements
that
are
executed
as
a
single
unit
of
work.
Transactions
ensure
data
consistency,
integrity,
and
reliability
in
a
database
by
grouping
related
operations
together
and
either
committing
or
rolling
back
changes
based
on
the
success
or
failure
of
those
operations.
There
are
three
main
TCL
commands
in
SQL:
COMMIT,
ROLLBACK,
and
SAVEPOINT.
1.
COMMIT:
The
COMMIT
command
is
used
to
permanently
save
the
changes
made
during
a
transaction.

It
makes
all
the
changes
applied
to
the
database
since
the
last
COMMIT
or
ROLLBACK
command
permanent.
Once
a
COMMIT
is
executed,
the
transaction
is
considered
successful,
and
the
changes
are
made
permanent.
Example:
Committing
changes
made
during
a
transaction:
UPDATE
Employees
SET
Salary
=
Salary
*
1.10
WHERE
Department
=
'Sales';
COMMIT;
2.
ROLLBACK:
The
ROLLBACK
command
is
used
to
undo
changes
made
during
a
transaction.
It
reverts
all
the
changes
applied
to
the
database
since
the
transaction
began.
ROLLBACK
is
typically
used
when
an
error
occurs
during
the
execution
of
a
transaction,
ensuring
that
the
database
remains
in
a
consistent
state.
Example:
Rolling
back
changes
due
to
an
error
during
a
transaction:
BEGIN;
UPDATE
Inventory
SET
Quantity
=
Quantity
-
10
WHERE
ProductID
=
101;
--
An
error
occurs
here
ROLLBACK;
3.
SAVEPOINT:
The
SAVEPOINT
command
creates
a
named
point
within
a
transaction,
allowing
you
to
set
a
point
to
which
you
can
later
ROLLBACK
if
needed.
SAVEPOINTs
are
useful
when
you
want
to
undo
part
of
a
transaction
while
preserving
other
changes.
Syntax:
SAVEPOINT
savepoint_name;
Example:
Using
SAVEPOINT
to
create
a
point
within
a
transaction:
BEGIN;

UPDATE
Accounts
SET
Balance
=
Balance
-
100
WHERE
AccountID
=
123;
SAVEPOINT
before_withdrawal;
UPDATE
Accounts
SET
Balance
=
Balance
+
100
WHERE
AccountID
=
456;
--
An
error
occurs
here
ROLLBACK
TO
before_withdrawal;
--
The
first
update
is
still
applied
COMMIT;
TCL
and
Transaction
Management:
Transaction
Control
Language
(TCL)
commands
are
vital
for
managing
the
integrity
and
consistency
of
a
database's
data.
They
allow
you
to
group
related
changes
into
transactions,
and
in
the
event
of
errors,
either
commit
those
changes
or
roll
them
back
to
maintain
data
integrity.
TCL
commands
are
used
in
combination
with
Data
Manipulation
Language
(DML)
and
other
SQL
commands
to
ensure
that
the
database
remains
in
a
reliable
state
despite
unforeseen
errors
or
issues.
JOINS
In
a
DBMS,
a
join
is
an
operation
that
combines
rows
from
two
or
more
tables
based
on
a
related
column
between
them.
Joins
are
used
to
retrieve
data
from
multiple
tables
by
linking
them
together
using
a
common
key
or
column.
Types
of
Joins:

1.
Inner
Join
2.
Outer
Join
3.
Cross
Join
4.
Self
Join
1)
Inner
Join
An
inner
join
combines
data
from
two
or
more
tables
based
on
a
specified
condition,
known
as
the
join
condition.
The
result
of
an
inner
join
includes
only
the
rows
where
the
join
condition
is
met
in
all
participating
tables.
It
essentially
filters
out
non-matching
rows
and
returns
only
the
rows
that
have
matching
values
in
both
tables.
Syntax:
SELECT
columns
FROM
table1
INNER
JOIN
table2
ON
table1.column
=
table2.column;
Here:
●
columns
refers
to
the
specific
columns
you
want
to
retrieve
from
the
tables.
●
table1
and
table2
are
the
names
of
the
tables
you
are
joining.
●
column
is
the
common
column
used
to
match
rows
between
the
tables.
●
The
ON
clause
specifies
the
join
condition,
where
you
define
how
the
tables
are
related.
Example:
Consider
two
tables:
Customers
and
Orders.
Customers
Table:
CustomerID
CustomerName
1
Alice
2
Bob
3
Carol
Orders
Table:
OrderID
CustomerID
Product

101
1
Laptop
102
3
Smartphone
103
2
Headphones
Inner
Join
Query:
SELECT
Customers.CustomerName,
Orders.Product
FROM
Customers
INNER
JOIN
Orders
ON
Customers.CustomerID
=
Orders.CustomerID;
Result:
CustomerName
Product
Alice
Laptop
Bob
Headphones
Carol
Smartphone
2)
Outer
Join
Outer
joins
combine
data
from
two
or
more
tables
based
on
a
specified
condition,
just
like
inner
joins.
However,
unlike
inner
joins,
outer
joins
also
include
rows
that
do
not
have
matching
values
in
both
tables.
Outer
joins
are
particularly
useful
when
you
want
to
include
data
from
one
table
even
if
there
is
no
corresponding
match
in
the
other
table.
Types
:
There
are
three
types
of
outer
joins:
left
outer
join,
right
outer
join,
and
full
outer
join.
1.
Left
Outer
Join
(Left
Join):
A
left
outer
join
returns
all
the
rows
from
the
left
table
and
the
matching
rows
from
the
right
table.

If
there
is
no
match
in
the
right
table,
the
result
will
still
include
the
left
table's
row
with
NULL
values
in
the
right
table's
columns.
Example:
SELECT
Customers.CustomerName,
Orders.Product
FROM
Customers
LEFT
JOIN
Orders
ON
Customers.CustomerID
=
Orders.CustomerID;
Result:
CustomerName
Product
Alice
Laptop
Bob
Headphones
Carol
Smartphone
NULL
Monitor
In
this
example,
the
left
outer
join
includes
all
rows
from
the
Customers
table.
Since
there

BadRequestError: Error code: 400 - {'error': {'message': 'Please reduce the length of the messages or completion.', 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

Map Reduce Technique

In [33]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

In [34]:
final_docs=RecursiveCharacterTextSplitter(chunk_size=500,chunk_overlap=100).split_documents(docs)
final_docs

[Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 0}, page_content='SQL\n(Notes\nby\nApna\nCollege)\nWhat\nis\nDatabase?\nDatabase\nis\na\ncollection\nof\ninterrelated\ndata.\nWhat\nis\nDBMS?\nDBMS\n(\nDatabase\nManagement\nSystem\n)\nis\nsoftware\nused\nto\ncreate,\nmanage,\nand\norganize\ndatabases.\nWhat\nis\nRDBMS?\n●\nRDBMS\n(Relational\nDatabase\nManagement\nSystem)\n-\nis\na\nDBMS\nbased\non\nthe\nconcept\nof\ntables\n(also\ncalled\nrelations).\n●\nData\nis\norganized\ninto\ntables\n(also\nknown\nas\nrelations)\nwith\nrows\n(records)\nand\ncolumns\n(attributes).\n●\nEg\n-\nMySQL,\nPostgreSQL,\nOracle\netc.\nWhat\nis\nSQL?\nSQL\nis'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 0}, page_content='rows\n(records)\nand\ncolumns\n(attributes).\n●\nEg\n-\nMySQL,\nPostgreSQL,\nOracle\netc.\nWhat\nis\nSQL?\nSQL\nis\nStructured\nQuery\nLanguage\n-\nused\nto\nstore,\nmanipulate\nand\nretrieve\ndata\nfrom\nRDBMS.\n(It\nis\nnot\na\ndatabase,\nit\nis\na\nlanguage\nused\nto\ninteract\nwith\ndatabase)\nWe\nuse\nSQL\nfor\nCRUD\nOperations\n:\n●\nCREATE\n-\nTo\ncreate\ndatabases,\ntables,\ninsert\ntuples\nin\ntables\netc\n●\nREAD\n-\nTo\nread\ndata\npresent\nin\nthe\ndatabase.\n●\nUPDATE\n-\nModify\nalready\ninserted\ndata.\n●\nDELETE\n-\nDelete\ndatabase,\ntable\nor\nspecific\ndata'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 0}, page_content='●\nUPDATE\n-\nModify\nalready\ninserted\ndata.\n●\nDELETE\n-\nDelete\ndatabase,\ntable\nor\nspecific\ndata\npoint/tuple/row\nor\nmultiple\nrows.\n*Note\n-\nSQL\nkeywords\nare\nNOT\ncase\nsensitive.\nEg:\nselect\nis\nthe\nsame\nas\nSELECT\nin\nSQL.\nSQL\nv/s\nMySQL\nSQL\nis\na\nlanguage\nused\nto\nperform\nCRUD\noperations\nin\nRelational\nDB,\nwhile\nMySQL\nis\na\nRDBMS\nthat\nuses\nSQL.'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 1}, page_content='SQL\nData\nTypes\nIn\nSQL,\ndata\ntypes\ndefine\nthe\nkind\nof\ndata\nthat\ncan\nbe\nstored\nin\na\ncolumn\nor\nvariable.\nTo\nSee\nall\ndata\ntypes\nof\nMYSQL,\nvisit\n:\nhttps://dev.mysql.com/doc/refman/8.0/en/data-types.html\nHere\nare\nthe\nfrequently\nused\nSQL\ndata\ntypes:\nDATATYPE\nDESCRIPTION\nUSAGE\nCHAR\nstring(0-255),\ncan\nstore\ncharacters\nof\nfixed\nlength\nCHAR(50)\nVARCHAR\nstring(0-255),\ncan\nstore\ncharacters\nup\nto\ngiven\nlength\nVARCHAR(50)\nBLOB\nstring(0-65535),\ncan\nstore\nbinary\nlarge\nobject\nBLOB(1000)\nINT\ninteger('),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 1}, page_content='length\nVARCHAR(50)\nBLOB\nstring(0-65535),\ncan\nstore\nbinary\nlarge\nobject\nBLOB(1000)\nINT\ninteger(\n-2,147,483,648\nto\n2,147,483,647\n)\nINT\nTINYINT\ninteger(-128\nto\n127)\nTINYINT\nBIGINT\ninteger(\n-9,223,372,036,854,775,808\nto \n9,223,372,036,854,775,807\n)\nBIGINT\nBIT\ncan\nstore\nx-bit\nvalues.\nx\ncan\nrange\nfrom\n1\nto\n64\nBIT(2)\nFLOAT\nDecimal\nnumber\n-\nwith\nprecision\nto\n23\ndigits\nFLOAT\nDOUBLE\nDecimal\nnumber\n-\nwith\n24\nto\n53\ndigits\nDOUBLE\nBOOLEAN\nBoolean\nvalues\n0\nor\n1\nBOOLEAN\nDATE\ndate\nin\nformat\nof\nYYYY-MM-DD'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 1}, page_content='with\n24\nto\n53\ndigits\nDOUBLE\nBOOLEAN\nBoolean\nvalues\n0\nor\n1\nBOOLEAN\nDATE\ndate\nin\nformat\nof\nYYYY-MM-DD\nranging\nfrom \n1000-01-01\nto\n9999-12-31\nDATE\nTIME\nHH:MM:SS\nTIME\nYEAR\nyear\nin\n4\ndigits\nformat\nranging\nfrom\n1901\nto\n2155\nYEAR\n*Note\n-\nCHAR\nis\nfor\nfixed\nlength\n&\nVARCHAR\nis\nfor\nvariable\nlength\nstrings.\nGenerally,\nVARCHAR\nis\nbetter\nas\nit\nonly\noccupies\nnecessary\nmemory\n&\nworks\nmore\nefficiently.\nWe\ncan\nalso\nuse\nUNSIGNED\nwith\ndatatypes\nwhen\nwe\nonly\nhave\npositive\nvalues\nto\nadd.\nEg\n-\nUNSIGNED\nINT\nTypes\nof'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 1}, page_content='use\nUNSIGNED\nwith\ndatatypes\nwhen\nwe\nonly\nhave\npositive\nvalues\nto\nadd.\nEg\n-\nUNSIGNED\nINT\nTypes\nof\nSQL\nCommands:'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 2}, page_content='1.\nDQL\n(Data\nQuery\nLanguage)\n:\nUsed\nto\nretrieve\ndata\nfrom\ndatabases.\n(SELECT)\n2.\nDDL\n(Data\nDefinition\nLanguage)\n:\nUsed\nto\ncreate,\nalter,\nand\ndelete\ndatabase\nobjects\nlike\ntables,\nindexes,\netc.\n(CREATE,\nDROP,\nALTER,\nRENAME,\nTRUNCATE)\n3.\nDML\n(Data\nManipulation\nLanguage)\n:\nUsed\nto\nmodify\nthe\ndatabase.\n(INSERT,\nUPDATE,\nDELETE)\n4.\nDCL\n(Data\nControl\nLanguage)\n:\nUsed\nto\ngrant\n&\nrevoke\npermissions.\n(GRANT,\nREVOKE)\n5.\nTCL\n(Transaction\nControl\nLanguage)\n:\nUsed\nto\nmanage\ntransactions.\n(COMMIT,\nROLLBACK,'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 2}, page_content='REVOKE)\n5.\nTCL\n(Transaction\nControl\nLanguage)\n:\nUsed\nto\nmanage\ntransactions.\n(COMMIT,\nROLLBACK,\nSTART\nTRANSACTIONS,\nSAVEPOINT)\n1.\nData\nDefinition\nLanguage\n(DDL)\nData\nDefinition\nLanguage\n(DDL)\nis\na\nsubset\nof\nSQL\n(Structured\nQuery\nLanguage)\nresponsible\nfor\ndefining\nand\nmanaging\nthe\nstructure\nof\ndatabases\nand\ntheir\nobjects.\nDDL\ncommands\nenable\nyou\nto\ncreate,\nmodify,\nand\ndelete\ndatabase\nobjects\nlike\ntables,\nindexes,\nconstraints,\nand\nmore.\nKey\nDDL\nCommands\nare:\n●\nCREATE\nTABLE:\n○\nUsed\nto\ncreate\na\nnew'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 2}, page_content='indexes,\nconstraints,\nand\nmore.\nKey\nDDL\nCommands\nare:\n●\nCREATE\nTABLE:\n○\nUsed\nto\ncreate\na\nnew\ntable\nin\nthe\ndatabase.\n○\nSpecifies\nthe\ntable\nname,\ncolumn\nnames,\ndata\ntypes,\nconstraints,\nand\nmore.\n○\nExample:\nCREATE\nTABLE\nemployees\n(id\nINT\nPRIMARY\nKEY,\nname\nVARCHAR(50),\nsalary\nDECIMAL(10,\n2));\n●\nALTER\nTABLE:\n○\nUsed\nto\nmodify\nthe\nstructure\nof\nan\nexisting\ntable.\n○\nYou\ncan\nadd,\nmodify,\nor\ndrop\ncolumns,\nconstraints,\nand\nmore.\n○\nExample:\nALTER\nTABLE\nemployees\nADD\nCOLUMN\nemail\nVARCHAR(100);\n●\nDROP\nTABLE:'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 2}, page_content='and\nmore.\n○\nExample:\nALTER\nTABLE\nemployees\nADD\nCOLUMN\nemail\nVARCHAR(100);\n●\nDROP\nTABLE:\n○\nUsed\nto\ndelete\nan\nexisting\ntable\nalong\nwith\nits\ndata\nand\nstructure.\n○\nExample:\nDROP\nTABLE\nemployees;'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 3}, page_content='●\nCREATE\nINDEX:\n○\nUsed\nto\ncreate\nan\nindex\non\none\nor\nmore\ncolumns\nin\na\ntable.\n○\nImproves\nquery\nperformance\nby\nenabling\nfaster\ndata\nretrieval.\n○\nExample:\nCREATE\nINDEX\nidx_employee_name\nON\nemployees\n(name);\n●\nDROP\nINDEX:\n○\nUsed\nto\nremove\nan\nexisting\nindex\nfrom\na\ntable.\n○\nExample:\nDROP\nINDEX\nidx_employee_name;\n●\nCREATE\nCONSTRAINT:\n○\nUsed\nto\ndefine\nconstraints\nthat\nensure\ndata\nintegrity.\n○\nConstraints\ninclude\nPRIMARY\nKEY,\nFOREIGN\nKEY,\nUNIQUE,\nNOT\nNULL,\nand\nCHECK.\n○\nExample:\nALTER\nTABLE\norders\nADD'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 3}, page_content='include\nPRIMARY\nKEY,\nFOREIGN\nKEY,\nUNIQUE,\nNOT\nNULL,\nand\nCHECK.\n○\nExample:\nALTER\nTABLE\norders\nADD\nCONSTRAINT\nfk_customer\nFOREIGN\nKEY\n(customer_id)\nREFERENCES\ncustomers(id);\n●\nDROP\nCONSTRAINT:\n○\nUsed\nto\nremove\nan\nexisting\nconstraint\nfrom\na\ntable.\n○\nExample:\nALTER\nTABLE\norders\nDROP\nCONSTRAINT\nfk_customer;\n●\nTRUNCATE\nTABLE:\n○\nUsed\nto\ndelete\nthe\ndata\ninside\na\ntable,\nbut\nnot\nthe\ntable\nitself.\n○\nSyntax\n–\nTRUNCATE\nTABLE\ntable_name\n2.\nDATA\nQUER Y/RETRIEV AL\nLANGUAGE\n(DQL\nor\nDRL)\nDQL\n(Data\nQuery'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 3}, page_content='Syntax\n–\nTRUNCATE\nTABLE\ntable_name\n2.\nDATA\nQUER Y/RETRIEV AL\nLANGUAGE\n(DQL\nor\nDRL)\nDQL\n(Data\nQuery\nLanguage)\nis\na\nsubset\nof\nSQL\nfocused\non\nretrieving\ndata\nfrom\ndatabases.\nThe\nSELECT\nstatement\nis\nthe\nfoundation\nof\nDQL\nand\nallows\nus\nto\nextract\nspecific\ncolumns\nfrom\na\ntable.\n●\nSELECT:\nThe\nSELECT\nstatement\nis\nused\nto\nselect\ndata\nfrom\na\ndatabase.'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 4}, page_content="Syntax:\nSELECT\ncolumn1,\ncolumn2,\n...\nFROM\ntable_name;\nHere,\ncolumn1,\ncolumn2,\n...\nare\nthe\nfield\nnames\nof\nthe\ntable.\nIf\nyou\nwant\nto\nselect\nall\nthe\nfields\navailable\nin\nthe\ntable,\nuse\nthe\nfollowing\nsyntax:\nSELECT\n*\nFROM\ntable_name;\nEx:\nSELECT\nCustomerName,\nCity\nFROM\nCustomers;\n●\nWHERE:\nThe\nWHERE\nclause\nis\nused\nto\nfilter\nrecords.\nSyntax:\nSELECT\ncolumn1,\ncolumn2,\n...\nFROM\ntable_name\nWHERE\ncondition;\nEx:\nSELECT\n*\nFROM\nCustomers\nWHERE\nCountry='Mexico';\nOperators\nused\nin\nWHERE\nare:\n=\n:\nEqual\n>\n:\nGreater"),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 4}, page_content="SELECT\n*\nFROM\nCustomers\nWHERE\nCountry='Mexico';\nOperators\nused\nin\nWHERE\nare:\n=\n:\nEqual\n>\n:\nGreater\nthan\n<\n:\nLess\nthan\n>=\n:\nGreater\nthan\nor\nequal\n<=\n:\nLess\nthan\nor\nequal\n<>\n:\nNot\nequal.\nNote:\nIn\nsome\nversions\nof\nSQL\nthis\noperator\nmay\nbe\nwritten\nas\n!=\n●\nAND,\nOR\nand\nNOT:\n-\nThe\nWHERE\nclause\ncan\nbe\ncombined\nwith\nAND,\nOR,\nand\nNOT\noperators.\n-\nThe\nAND\nand\nOR\noperators\nare\nused\nto\nfilter\nrecords\nbased\non\nmore\nthan\none\ncondition:\n-\nThe\nAND\noperator\ndisplays\na\nrecord\nif\nall\nthe\nconditions\nseparated\nby"),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 4}, page_content='on\nmore\nthan\none\ncondition:\n-\nThe\nAND\noperator\ndisplays\na\nrecord\nif\nall\nthe\nconditions\nseparated\nby\nAND\nare\nTRUE.\n-\nThe\nOR\noperator\ndisplays\na\nrecord\nif\nany\nof\nthe\nconditions\nseparated\nby\nOR\nis\nTRUE.\n-\nThe\nNOT\noperator\ndisplays\na\nrecord\nif\nthe\ncondition(s)\nis\nNOT\nTRUE.\nSyntax:'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 5}, page_content='SELECT\ncolumn1,\ncolumn2,\n...\nFROM\ntable_name\nWHERE\ncondition1\nAND\ncondition2\nAND\ncondition3\n...;\nSELECT\ncolumn1,\ncolumn2,\n...\nFROM\ntable_name\nWHERE\ncondition1\nOR\ncondition2\nOR\ncondition3\n...;\nSELECT\ncolumn1,\ncolumn2,\n...\nFROM\ntable_name\nWHERE\nNOT\ncondition;\nExample:\nSELECT\n*\nFROM\nCustomers\nWHERE\nCountry=’India’\nAND\nCity=’Japan’;\nSELECT\n*\nFROM\nCustomers\nWHERE\nCountry=’America’\nAND\n(City=’India’\nOR\nCity=’Korea’);\n●\nDISTINCT:\nRemoves\nduplicate\nrows\nfrom\nquery\nresults.\nSyntax:\nSELECT\nDISTINCT'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 5}, page_content="OR\nCity=’Korea’);\n●\nDISTINCT:\nRemoves\nduplicate\nrows\nfrom\nquery\nresults.\nSyntax:\nSELECT\nDISTINCT\ncolumn1,\ncolumn2\nFROM\ntable_name;\n●\nLIKE\n:\nThe\nLIKE\noperator\nis\nused\nin\na\nWHERE\nclause\nto\nsearch\nfor\na\nspecified\npattern\nin\na\ncolumn.\nThere\nare\ntwo\nwildcards\noften\nused\nin\nconjunction\nwith\nthe\nLIKE\noperator:\n-\nThe\npercent\nsign\n(%)\nrepresents\nzero,\none,\nor\nmultiple\ncharacters\n-\nThe\nunderscore\nsign\n(_)\nrepresents\none,\nsingle\ncharacter\nExample:\nSELECT\n*\nFROM\nemployees\nWHERE\nfirst_name\nLIKE\n'J%';\nWHERE"),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 5}, page_content='represents\none,\nsingle\ncharacter\nExample:\nSELECT\n*\nFROM\nemployees\nWHERE\nfirst_name\nLIKE\n\'J%\';\nWHERE\nCustomerName\nLIKE\n\'a%\'\n-\nFinds\nany\nvalues\nthat\nstart\nwith\n"a"\nWHERE\nCustomerName\nLIKE\n\'%a\'\n-\nFinds\nany\nvalues\nthat\nend\nwith\n"a"\nWHERE\nCustomerName\nLIKE\n\'%or%\'\n-\nFinds\nany\nvalues\nthat\nhave\n"or"\nin\nany\nposition\nWHERE\nCustomerName\nLIKE\n\'_r%\'\n-\nFinds\nany\nvalues\nthat\nhave\n"r"\nin\nthe\nsecond\nposition'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 6}, page_content='WHERE\nCustomerName\nLIKE\n\'a_%\'\n-\nFinds\nany\nvalues\nthat\nstart\nwith\n"a"\nand\nare\nat\nleast\n2\ncharacters\nin\nlength\nWHERE\nCustomerName\nLIKE\n\'a__%\'\n-\nFinds\nany\nvalues\nthat\nstart\nwith\n"a"\nand\nare\nat\nleast\n3\ncharacters\nin\nlength\nWHERE\nContactName\nLIKE\n\'a%o\'\n-\nFinds\nany\nvalues\nthat\nstart\nwith\n"a"\nand\nends\nwith\n"o"\n●\nIN:\nFilters\nresults\nbased\non\na\nlist\nof\nvalues\nin\nthe\nWHERE\nclause.\nExample:\nSELECT\n*\nFROM\nproducts\nWHERE\ncategory_id\nIN\n(1,\n2,\n3);\n●\nBETWEEN\n:\nFilters\nresults\nwithin\na\nspecified\nrange\nin\nthe'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 6}, page_content='WHERE\ncategory_id\nIN\n(1,\n2,\n3);\n●\nBETWEEN\n:\nFilters\nresults\nwithin\na\nspecified\nrange\nin\nthe\nWHERE\nclause.\nExample:\nSELECT\n*\nFROM\norders\nWHERE\norder_date\nBETWEEN\n\'2023-01-01\'\nAND\n\'2023-06-30\';\n●\nIS\nNULL\n:\nChecks\nfor\nNULL\nvalues\nin\nthe\nWHERE\nclause.\nExample:\nSELECT\n*\nFROM\ncustomers\nWHERE\nemail\nIS\nNULL;\n●\nAS\n:\nRenames\ncolumns\nor\nexpressions\nin\nquery\nresults.\nExample:\nSELECT\nfirst_name\nAS\n"First\nName",\nlast_name\nAS\n"Last\nName"\nFROM\nemployees;\n●\nORDER\nBY\nThe\nORDER\nBY\nclause\nallows\nyou\nto\nsort\nthe'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 6}, page_content='last_name\nAS\n"Last\nName"\nFROM\nemployees;\n●\nORDER\nBY\nThe\nORDER\nBY\nclause\nallows\nyou\nto\nsort\nthe\nresult\nset\nof\na\nquery\nbased\non\none\nor\nmore\ncolumns.\nBasic\nSyntax:\n-\nThe\nORDER\nBY\nclause\nis\nused\nafter\nthe\nSELECT\nstatement\nto\nsort\nquery\nresults.'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 7}, page_content='-\nSyntax:\nSELECT\ncolumn1,\ncolumn2\nFROM\ntable_name\nORDER\nBY\ncolumn1\n[ASC|DESC];\nAscending\nand\nDescending\nOrder:\n-\nBy\ndefault,\nthe\nORDER\nBY\nclause\nsorts\nin\nascending\norder\n(smallest\nto\nlargest).\n-\nYou\ncan\nexplicitly\nspecify\ndescending\norder\nusing\nthe\nDESC\nkeyword.\n-\nExample:\nSELECT\nproduct_name,\nprice\nFROM\nproducts\nORDER\nBY\nprice\nDESC;\nSorting\nby\nMultiple\nColumns:\n-\nYou\ncan\nsort\nby\nmultiple\ncolumns\nby\nlisting\nthem\nsequentially\nin\nthe\nORDER\nBY\nclause.\n-\nRows\nare\nfirst\nsorted\nbased\non\nthe\nfirst'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 7}, page_content="by\nlisting\nthem\nsequentially\nin\nthe\nORDER\nBY\nclause.\n-\nRows\nare\nfirst\nsorted\nbased\non\nthe\nfirst\ncolumn,\nand\nfor\nrows\nwith\nequal\nvalues,\nsubsequent\ncolumns\nare\nused\nfor\nfurther\nsorting.\n-\nExample:\nSELECT\nfirst_name,\nlast_name\nFROM\nemployees\nORDER\nBY\nlast_name,\nfirst_name;\nSorting\nby\nExpressions:\n-\nIt's\npossible\nto\nsort\nby\ncalculated\nexpressions,\nnot\njust\ncolumn\nvalues.\n-\nExample:\nSELECT\nproduct_name,\nprice,\nprice\n*\n1.1\nAS\ndiscounted_price\nFROM\nproducts\nORDER\nBY\ndiscounted_price;\nSorting\nNULL"),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 7}, page_content='price,\nprice\n*\n1.1\nAS\ndiscounted_price\nFROM\nproducts\nORDER\nBY\ndiscounted_price;\nSorting\nNULL\nValues:\n-\nBy\ndefault,\nNULL\nvalues\nare\nconsidered\nthe\nsmallest\nin\nascending\norder\nand\nthe\nlargest\nin\ndescending\norder.\n-\nYou\ncan\ncontrol\nthe\nsorting\nbehaviour\nof\nNULL\nvalues\nusing\nthe\nNULLS\nFIRST\nor\nNULLS\nLAST\noptions.\n-\nExample:\nSELECT\ncolumn_name\nFROM\ntable_name\nORDER\nBY\ncolumn_name\nNULLS\nLAST;\nSorting\nby\nPosition:\n-\nInstead\nof\nspecifying\ncolumn\nnames,\nyou\ncan\nsort\nby\ncolumn\npositions\nin\nthe\nORDER\nBY'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 7}, page_content='by\nPosition:\n-\nInstead\nof\nspecifying\ncolumn\nnames,\nyou\ncan\nsort\nby\ncolumn\npositions\nin\nthe\nORDER\nBY\nclause.\n-\nExample:\nSELECT\nproduct_name,\nprice\nFROM\nproducts\nORDER\nBY\n2\nDESC,\n1\nASC;\n●\nGROUP\nBY\nThe\nGROUP\nBY\nclause\nin\nSQL\nis\nused\nto\ngroup\nrows\nfrom\na\ntable\nbased\non\none\nor\nmore\ncolumns.\nSyntax:'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 8}, page_content='-\nThe\nGROUP\nBY\nclause\nfollows\nthe\nSELECT\nstatement\nand\nis\nused\nto\ngroup\nrows\nbased\non\nspecified\ncolumns.\n-\nSyntax:\nSELECT\ncolumn1,\naggregate_function(column2)\nFROM\ntable_name\nGROUP\nBY\ncolumn1;\n-\nAggregation\nFunctions:\n○\nAggregation\nfunctions\n(e.g.,\nCOUNT,\nSUM,\nAVG,\nMAX,\nMIN)\nare\noften\nused\nwith\nGROUP\nBY\nto\ncalculate\nvalues\nfor\neach\ngroup.\n○\nExample:\nSELECT\ndepartment,\nAVG(salary)\nFROM\nemployees\nGROUP\nBY\ndepartment;\n-\nGrouping\nby\nMultiple\nColumns:\n○\nYou\ncan\ngroup\nby\nmultiple\ncolumns\nby\nlisting'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 8}, page_content="GROUP\nBY\ndepartment;\n-\nGrouping\nby\nMultiple\nColumns:\n○\nYou\ncan\ngroup\nby\nmultiple\ncolumns\nby\nlisting\nthem\nin\nthe\nGROUP\nBY\nclause.\n○\nThis\ncreates\na\nhierarchical\ngrouping\nbased\non\nthe\nspecified\ncolumns.\n○\nExample:\nSELECT\ndepartment,\ngender,\nAVG(salary)\nFROM\nemployees\nGROUP\nBY\ndepartment,\ngender;\n-\nHAVING\nClause:\n○\nThe\nHAVING\nclause\nis\nused\nwith\nGROUP\nBY\nto\nfilter\ngroups\nbased\non\naggregate\nfunction\nresults.\n○\nIt's\nsimilar\nto\nthe\nWHERE\nclause\nbut\noperates\non\ngrouped\ndata.\n○\nExample:\nSELECT"),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 8}, page_content="results.\n○\nIt's\nsimilar\nto\nthe\nWHERE\nclause\nbut\noperates\non\ngrouped\ndata.\n○\nExample:\nSELECT\ndepartment,\nAVG(salary)\nFROM\nemployees\nGROUP\nBY\ndepartment\nHAVING\nAVG(salary)\n>\n50000;\n-\nCombining\nGROUP\nBY\nand\nORDER\nBY:\n○\nYou\ncan\nuse\nboth\nGROUP\nBY\nand\nORDER\nBY\nin\nthe\nsame\nquery\nto\ncontrol\nthe\norder\nof\ngrouped\nresults.\n○\nExample:\nSELECT\ndepartment,\nCOUNT(*)\nFROM\nemployees\nGROUP\nBY\ndepartment\nORDER\nBY\nCOUNT(*)\nDESC;\n●\nAGGREGATE\nFUNCTIONS\nThese\nare\nused\nto\nperform\ncalculations\non\ngroups\nof\nrows\nor"),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 8}, page_content='BY\nCOUNT(*)\nDESC;\n●\nAGGREGATE\nFUNCTIONS\nThese\nare\nused\nto\nperform\ncalculations\non\ngroups\nof\nrows\nor\nentire\nresult\nsets.\nThey\nprovide\ninsights\ninto\ndata\nby\nsummarising\nand\nprocessing\ninformation.\nCommon\nAggregate\nFunctions:\n-\nCOUNT():\nCounts\nthe\nnumber\nof\nrows\nin\na\ngroup\nor\nresult\nset.\n-\nSUM():\nCalculates\nthe\nsum\nof\nnumeric\nvalues\nin\na\ngroup\nor\nresult\nset.\n-\nAVG():'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 9}, page_content='Computes\nthe\naverage\nof\nnumeric\nvalues\nin\na\ngroup\nor\nresult\nset.\n-\nMAX():\nFinds\nthe\nmaximum\nvalue\nin\na\ngroup\nor\nresult\nset.\n-\nMIN():\nRetrieves\nthe\nminimum\nvalue\nin\na\ngroup\nor\nresult\nset.\n3.\nDATA\nMANIPULA TION\nLANGUAGE\nData\nManipulation\nLanguage\n(DML)\nin\nSQL\nencompasses\ncommands\nthat\nmanipulate\ndata\nwithin\na\ndatabase.\nDML\nallows\nyou\nto\ninsert,\nupdate,\nand\ndelete\nrecords,\nensuring\nthe\naccuracy\nand\ncurrency\nof\nyour\ndata.\n●\nINSERT:\n-\nThe\nINSERT\nstatement\nadds\nnew\nrecords\nto\na\ntable.\n-\nSyntax:\nINSERT'),
 Document(metadata={'source': 'SQL_Notes_by_Apna_College.pdf', 'page': 9}, page_content="of\nyour\ndata.\n●\nINSERT:\n-\nThe\nINSERT\nstatement\nadds\nnew\nrecords\nto\na\ntable.\n-\nSyntax:\nINSERT\nINTO\ntable_name\n(column1,\ncolumn2,\n...)\nVALUES\n(value1,\nvalue2,\n...);\n-\nExample:\nINSERT\nINTO\nemployees\n(first_name,\nlast_name,\nsalary)\nVALUES\n('John',\n'Doe',\n50000);\n●\nUPDATE\n:\n-\nThe\nUPDATE\nstatement\nmodifies\nexisting\nrecords\nin\na\ntable.\n-\nSyntax:\nUPDATE\ntable_name\nSET\ncolumn1\n=\nvalue1,\ncolumn2\n=\nvalue2,\n...\nWHERE\ncondition;\n-\nExample:\nUPDATE\nemployees\nSET\nsalary\n=\n55000\nWHERE\nfirst_name\n=\n'John';\n●"),

In [35]:
# this prompt we have craeted is for the chunks means 1st chunk will give 1st summary,2nd chunk will give 2nd summary and so on...
chunk_prompt="""
Please summarize the speech
speech:'{text}'
Summary:
"""
map_prompt_template=PromptTemplate(
    input_variables=('text'),
    template=chunk_prompt
)
map_prompt_template

PromptTemplate(input_variables=['text'], template="\nPlease summarize the speech\nspeech:'{text}'\nSummary:\n")

In [36]:
final_prompt=""" Provide the final summary of entire speech
speech:'{text}'
"""
final_prompt_template=PromptTemplate(
    input_variables=('text'),
    template=final_prompt
)
final_prompt_template

PromptTemplate(input_variables=['text'], template=" Provide the final summary of entire speech\nspeech:'{text}'\n")

In [40]:
# map_prompt_template this will give summary of different chunks 
# then we will combine all the different summaries and will give final summary i.e final_prompt_template
summary_chain=load_summarize_chain(model,chain_type='map_reduce',map_prompt=map_prompt_template,combine_prompt=final_prompt_template,verbose=True)
output_res=summary_chain.run(final_docs)
output_res

> Entering new MapReduceDocumentsChain chain...


> Entering new LLMChain chain...
Prompt after formatting:

Please summarize the speech
speech:'SQL
(Notes
by
Apna
College)
What
is
Database?
Database
is
a
collection
of
interrelated
data.
What
is
DBMS?
DBMS
(
Database
Management
System
)
is
software
used
to
create,
manage,
and
organize
databases.
What
is
RDBMS?
●
RDBMS
(Relational
Database
Management
System)
-
is
a
DBMS
based
on
the
concept
of
tables
(also
called
relations).
●
Data
is
organized
into
tables
(also
known
as
relations)
with
rows
(records)
and
columns
(attributes).
●
Eg
-
MySQL,
PostgreSQL,
Oracle
etc.
What
is
SQL?
SQL
is'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'rows
(records)
and
columns
(attributes).
●
Eg
-
MySQL,
PostgreSQL,
Oracle
etc.
What
is
SQL?
SQL
is
Structured
Query
Language
-
used
to
store,
manipulate
and
retrieve
data
from
RDBMS.
(It
is
not
a
database,
it
is
a
language
used
to
interact
with
database)
We
use
SQL
for
CRUD
Operations
:
●
CREATE
-
To
create
databases,
tables,
insert
tuples
in
tables
etc
●
READ
-
To
read
data
present
in
the
database.
●
UPDATE
-
Modify
already
inserted
data.
●
DELETE
-
Delete
database,
table
or
specific
data'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'●
UPDATE
-
Modify
already
inserted
data.
●
DELETE
-
Delete
database,
table
or
specific
data
point/tuple/row
or
multiple
rows.
*Note
-
SQL
keywords
are
NOT
case
sensitive.
Eg:
select
is
the
same
as
SELECT
in
SQL.
SQL
v/s
MySQL
SQL
is
a
language
used
to
perform
CRUD
operations
in
Relational
DB,
while
MySQL
is
a
RDBMS
that
uses
SQL.'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'SQL
Data
Types
In
SQL,
data
types
define
the
kind
of
data
that
can
be
stored
in
a
column
or
variable.
To
See
all
data
types
of
MYSQL,
visit
:
https://dev.mysql.com/doc/refman/8.0/en/data-types.html
Here
are
the
frequently
used
SQL
data
types:
DATATYPE
DESCRIPTION
USAGE
CHAR
string(0-255),
can
store
characters
of
fixed
length
CHAR(50)
VARCHAR
string(0-255),
can
store
characters
up
to
given
length
VARCHAR(50)
BLOB
string(0-65535),
can
store
binary
large
object
BLOB(1000)
INT
integer('
Summary:

Prompt after formatting:

Please summarize the speech
speech:'length
VARCHAR(50)
BLOB
string(0-65535),
can
store
binary
large
object
BLOB(1000)
INT
integer(
-2,147,483,648
to
2,147,483,647
)
INT
TINYINT
integer(-128
to
127)
TINYINT
BIGINT
integer(
-9,223,372,036,854,775,808
to
9,223,372,036,854,775,807
)
BIGINT
BIT
can
store
x-bit
values.
x
can
range
from
1
to
64
BIT(2)
FLOAT
Decimal
number
-
with
precision
to
23
digits
FLOAT
DOUBLE
Decimal
number
-
with
24
to
53
digits
DOUBLE
BOOLEAN
Boolean
values
0
or
1
BOOLEAN
DATE
date
in
format
of
YYYY-MM-DD'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'with
24
to
53
digits
DOUBLE
BOOLEAN
Boolean
values
0
or
1
BOOLEAN
DATE
date
in
format
of
YYYY-MM-DD
ranging
from
1000-01-01
to
9999-12-31
DATE
TIME
HH:MM:SS
TIME
YEAR
year
in
4
digits
format
ranging
from
1901
to
2155
YEAR
*Note
-
CHAR
is
for
fixed
length
&
VARCHAR
is
for
variable
length
strings.
Generally,
VARCHAR
is
better
as
it
only
occupies
necessary
memory
&
works
more
efficiently.
We
can
also
use
UNSIGNED
with
datatypes
when
we
only
have
positive
values
to
add.
Eg
-
UNSIGNED
INT
Types
of'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'use
UNSIGNED
with
datatypes
when
we
only
have
positive
values
to
add.
Eg
-
UNSIGNED
INT
Types
of
SQL
Commands:'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'1.
DQL
(Data
Query
Language)
:
Used
to
retrieve
data
from
databases.
(SELECT)
2.
DDL
(Data
Definition
Language)
:
Used
to
create,
alter,
and
delete
database
objects
like
tables,
indexes,
etc.
(CREATE,
DROP,
ALTER,
RENAME,
TRUNCATE)
3.
DML
(Data
Manipulation
Language)
:
Used
to
modify
the
database.
(INSERT,
UPDATE,
DELETE)
4.
DCL
(Data
Control
Language)
:
Used
to
grant
&
revoke
permissions.
(GRANT,
REVOKE)
5.
TCL
(Transaction
Control
Language)
:
Used
to
manage
transactions.
(COMMIT,
ROLLBACK,'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'REVOKE)
5.
TCL
(Transaction
Control
Language)
:
Used
to
manage
transactions.
(COMMIT,
ROLLBACK,
START
TRANSACTIONS,
SAVEPOINT)
1.
Data
Definition
Language
(DDL)
Data
Definition
Language
(DDL)
is
a
subset
of
SQL
(Structured
Query
Language)
responsible
for
defining
and
managing
the
structure
of
databases
and
their
objects.
DDL
commands
enable
you
to
create,
modify,
and
delete
database
objects
like
tables,
indexes,
constraints,
and
more.
Key
DDL
Commands
are:
●
CREATE
TABLE:
○
Used
to
create
a
new'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'indexes,
constraints,
and
more.
Key
DDL
Commands
are:
●
CREATE
TABLE:
○
Used
to
create
a
new
table
in
the
database.
○
Specifies
the
table
name,
column
names,
data
types,
constraints,
and
more.
○
Example:
CREATE
TABLE
employees
(id
INT
PRIMARY
KEY,
name
VARCHAR(50),
salary
DECIMAL(10,
2));
●
ALTER
TABLE:
○
Used
to
modify
the
structure
of
an
existing
table.
○
You
can
add,
modify,
or
drop
columns,
constraints,
and
more.
○
Example:
ALTER
TABLE
employees
ADD
COLUMN
email
VARCHAR(100);
●
DROP
TABLE:'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'and
more.
○
Example:
ALTER
TABLE
employees
ADD
COLUMN
email
VARCHAR(100);
●
DROP
TABLE:
○
Used
to
delete
an
existing
table
along
with
its
data
and
structure.
○
Example:
DROP
TABLE
employees;'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'●
CREATE
INDEX:
○
Used
to
create
an
index
on
one
or
more
columns
in
a
table.
○
Improves
query
performance
by
enabling
faster
data
retrieval.
○
Example:
CREATE
INDEX
idx_employee_name
ON
employees
(name);
●
DROP
INDEX:
○
Used
to
remove
an
existing
index
from
a
table.
○
Example:
DROP
INDEX
idx_employee_name;
●
CREATE
CONSTRAINT:
○
Used
to
define
constraints
that
ensure
data
integrity.
○
Constraints
include
PRIMARY
KEY,
FOREIGN
KEY,
UNIQUE,
NOT
NULL,
and
CHECK.
○
Example:
ALTER
TABLE
orders
ADD'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'include
PRIMARY
KEY,
FOREIGN
KEY,
UNIQUE,
NOT
NULL,
and
CHECK.
○
Example:
ALTER
TABLE
orders
ADD
CONSTRAINT
fk_customer
FOREIGN
KEY
(customer_id)
REFERENCES
customers(id);
●
DROP
CONSTRAINT:
○
Used
to
remove
an
existing
constraint
from
a
table.
○
Example:
ALTER
TABLE
orders
DROP
CONSTRAINT
fk_customer;
●
TRUNCATE
TABLE:
○
Used
to
delete
the
data
inside
a
table,
but
not
the
table
itself.
○
Syntax
–
TRUNCATE
TABLE
table_name
2.
DATA
QUER Y/RETRIEV AL
LANGUAGE
(DQL
or
DRL)
DQL
(Data
Query'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'Syntax
–
TRUNCATE
TABLE
table_name
2.
DATA
QUER Y/RETRIEV AL
LANGUAGE
(DQL
or
DRL)
DQL
(Data
Query
Language)
is
a
subset
of
SQL
focused
on
retrieving
data
from
databases.
The
SELECT
statement
is
the
foundation
of
DQL
and
allows
us
to
extract
specific
columns
from
a
table.
●
SELECT:
The
SELECT
statement
is
used
to
select
data
from
a
database.'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'Syntax:
SELECT
column1,
column2,
...
FROM
table_name;
Here,
column1,
column2,
...
are
the
field
names
of
the
table.
If
you
want
to
select
all
the
fields
available
in
the
table,
use
the
following
syntax:
SELECT
*
FROM
table_name;
Ex:
SELECT
CustomerName,
City
FROM
Customers;
●
WHERE:
The
WHERE
clause
is
used
to
filter
records.
Syntax:
SELECT
column1,
column2,
...
FROM
table_name
WHERE
condition;
Ex:
SELECT
*
FROM
Customers
WHERE
Country='Mexico';
Operators
used
in
WHERE
are:
=
:
Equal
>
:
Greater'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'SELECT
*
FROM
Customers
WHERE
Country='Mexico';
Operators
used
in
WHERE
are:
=
:
Equal
>
:
Greater
than
<
:
Less
than
>=
:
Greater
than
or
equal
<=
:
Less
than
or
equal
<>
:
Not
equal.
Note:
In
some
versions
of
SQL
this
operator
may
be
written
as
!=
●
AND,
OR
and
NOT:
-
The
WHERE
clause
can
be
combined
with
AND,
OR,
and
NOT
operators.
-
The
AND
and
OR
operators
are
used
to
filter
records
based
on
more
than
one
condition:
-
The
AND
operator
displays
a
record
if
all
the
conditions
separated
by'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'on
more
than
one
condition:
-
The
AND
operator
displays
a
record
if
all
the
conditions
separated
by
AND
are
TRUE.
-
The
OR
operator
displays
a
record
if
any
of
the
conditions
separated
by
OR
is
TRUE.
-
The
NOT
operator
displays
a
record
if
the
condition(s)
is
NOT
TRUE.
Syntax:'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'SELECT
column1,
column2,
...
FROM
table_name
WHERE
condition1
AND
condition2
AND
condition3
...;
SELECT
column1,
column2,
...
FROM
table_name
WHERE
condition1
OR
condition2
OR
condition3
...;
SELECT
column1,
column2,
...
FROM
table_name
WHERE
NOT
condition;
Example:
SELECT
*
FROM
Customers
WHERE
Country=’India’
AND
City=’Japan’;
SELECT
*
FROM
Customers
WHERE
Country=’America’
AND
(City=’India’
OR
City=’Korea’);
●
DISTINCT:
Removes
duplicate
rows
from
query
results.
Syntax:
SELECT
DISTINCT'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'OR
City=’Korea’);
●
DISTINCT:
Removes
duplicate
rows
from
query
results.
Syntax:
SELECT
DISTINCT
column1,
column2
FROM
table_name;
●
LIKE
:
The
LIKE
operator
is
used
in
a
WHERE
clause
to
search
for
a
specified
pattern
in
a
column.
There
are
two
wildcards
often
used
in
conjunction
with
the
LIKE
operator:
-
The
percent
sign
(%)
represents
zero,
one,
or
multiple
characters
-
The
underscore
sign
(_)
represents
one,
single
character
Example:
SELECT
*
FROM
employees
WHERE
first_name
LIKE
'J%';
WHERE'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'represents
one,
single
character
Example:
SELECT
*
FROM
employees
WHERE
first_name
LIKE
'J%';
WHERE
CustomerName
LIKE
'a%'
-
Finds
any
values
that
start
with
"a"
WHERE
CustomerName
LIKE
'%a'
-
Finds
any
values
that
end
with
"a"
WHERE
CustomerName
LIKE
'%or%'
-
Finds
any
values
that
have
"or"
in
any
position
WHERE
CustomerName
LIKE
'_r%'
-
Finds
any
values
that
have
"r"
in
the
second
position'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'WHERE
CustomerName
LIKE
'a_%'
-
Finds
any
values
that
start
with
"a"
and
are
at
least
2
characters
in
length
WHERE
CustomerName
LIKE
'a__%'
-
Finds
any
values
that
start
with
"a"
and
are
at
least
3
characters
in
length
WHERE
ContactName
LIKE
'a%o'
-
Finds
any
values
that
start
with
"a"
and
ends
with
"o"
●
IN:
Filters
results
based
on
a
list
of
values
in
the
WHERE
clause.
Example:
SELECT
*
FROM
products
WHERE
category_id
IN
(1,
2,
3);
●
BETWEEN
:
Filters
results
within
a
specified
range
in
the'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'WHERE
category_id
IN
(1,
2,
3);
●
BETWEEN
:
Filters
results
within
a
specified
range
in
the
WHERE
clause.
Example:
SELECT
*
FROM
orders
WHERE
order_date
BETWEEN
'2023-01-01'
AND
'2023-06-30';
●
IS
NULL
:
Checks
for
NULL
values
in
the
WHERE
clause.
Example:
SELECT
*
FROM
customers
WHERE
email
IS
NULL;
●
AS
:
Renames
columns
or
expressions
in
query
results.
Example:
SELECT
first_name
AS
"First
Name",
last_name
AS
"Last
Name"
FROM
employees;
●
ORDER
BY
The
ORDER
BY
clause
allows
you
to
sort
the'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'last_name
AS
"Last
Name"
FROM
employees;
●
ORDER
BY
The
ORDER
BY
clause
allows
you
to
sort
the
result
set
of
a
query
based
on
one
or
more
columns.
Basic
Syntax:
-
The
ORDER
BY
clause
is
used
after
the
SELECT
statement
to
sort
query
results.'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'-
Syntax:
SELECT
column1,
column2
FROM
table_name
ORDER
BY
column1
[ASC|DESC];
Ascending
and
Descending
Order:
-
By
default,
the
ORDER
BY
clause
sorts
in
ascending
order
(smallest
to
largest).
-
You
can
explicitly
specify
descending
order
using
the
DESC
keyword.
-
Example:
SELECT
product_name,
price
FROM
products
ORDER
BY
price
DESC;
Sorting
by
Multiple
Columns:
-
You
can
sort
by
multiple
columns
by
listing
them
sequentially
in
the
ORDER
BY
clause.
-
Rows
are
first
sorted
based
on
the
first'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'by
listing
them
sequentially
in
the
ORDER
BY
clause.
-
Rows
are
first
sorted
based
on
the
first
column,
and
for
rows
with
equal
values,
subsequent
columns
are
used
for
further
sorting.
-
Example:
SELECT
first_name,
last_name
FROM
employees
ORDER
BY
last_name,
first_name;
Sorting
by
Expressions:
-
It's
possible
to
sort
by
calculated
expressions,
not
just
column
values.
-
Example:
SELECT
product_name,
price,
price
*
1.1
AS
discounted_price
FROM
products
ORDER
BY
discounted_price;
Sorting
NULL'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'price,
price
*
1.1
AS
discounted_price
FROM
products
ORDER
BY
discounted_price;
Sorting
NULL
Values:
-
By
default,
NULL
values
are
considered
the
smallest
in
ascending
order
and
the
largest
in
descending
order.
-
You
can
control
the
sorting
behaviour
of
NULL
values
using
the
NULLS
FIRST
or
NULLS
LAST
options.
-
Example:
SELECT
column_name
FROM
table_name
ORDER
BY
column_name
NULLS
LAST;
Sorting
by
Position:
-
Instead
of
specifying
column
names,
you
can
sort
by
column
positions
in
the
ORDER
BY'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'by
Position:
-
Instead
of
specifying
column
names,
you
can
sort
by
column
positions
in
the
ORDER
BY
clause.
-
Example:
SELECT
product_name,
price
FROM
products
ORDER
BY
2
DESC,
1
ASC;
●
GROUP
BY
The
GROUP
BY
clause
in
SQL
is
used
to
group
rows
from
a
table
based
on
one
or
more
columns.
Syntax:'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'-
The
GROUP
BY
clause
follows
the
SELECT
statement
and
is
used
to
group
rows
based
on
specified
columns.
-
Syntax:
SELECT
column1,
aggregate_function(column2)
FROM
table_name
GROUP
BY
column1;
-
Aggregation
Functions:
○
Aggregation
functions
(e.g.,
COUNT,
SUM,
AVG,
MAX,
MIN)
are
often
used
with
GROUP
BY
to
calculate
values
for
each
group.
○
Example:
SELECT
department,
AVG(salary)
FROM
employees
GROUP
BY
department;
-
Grouping
by
Multiple
Columns:
○
You
can
group
by
multiple
columns
by
listing'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'GROUP
BY
department;
-
Grouping
by
Multiple
Columns:
○
You
can
group
by
multiple
columns
by
listing
them
in
the
GROUP
BY
clause.
○
This
creates
a
hierarchical
grouping
based
on
the
specified
columns.
○
Example:
SELECT
department,
gender,
AVG(salary)
FROM
employees
GROUP
BY
department,
gender;
-
HAVING
Clause:
○
The
HAVING
clause
is
used
with
GROUP
BY
to
filter
groups
based
on
aggregate
function
results.
○
It's
similar
to
the
WHERE
clause
but
operates
on
grouped
data.
○
Example:
SELECT'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'results.
○
It's
similar
to
the
WHERE
clause
but
operates
on
grouped
data.
○
Example:
SELECT
department,
AVG(salary)
FROM
employees
GROUP
BY
department
HAVING
AVG(salary)
>
50000;
-
Combining
GROUP
BY
and
ORDER
BY:
○
You
can
use
both
GROUP
BY
and
ORDER
BY
in
the
same
query
to
control
the
order
of
grouped
results.
○
Example:
SELECT
department,
COUNT(*)
FROM
employees
GROUP
BY
department
ORDER
BY
COUNT(*)
DESC;
●
AGGREGATE
FUNCTIONS
These
are
used
to
perform
calculations
on
groups
of
rows
or'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'BY
COUNT(*)
DESC;
●
AGGREGATE
FUNCTIONS
These
are
used
to
perform
calculations
on
groups
of
rows
or
entire
result
sets.
They
provide
insights
into
data
by
summarising
and
processing
information.
Common
Aggregate
Functions:
-
COUNT():
Counts
the
number
of
rows
in
a
group
or
result
set.
-
SUM():
Calculates
the
sum
of
numeric
values
in
a
group
or
result
set.
-
AVG():'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'Computes
the
average
of
numeric
values
in
a
group
or
result
set.
-
MAX():
Finds
the
maximum
value
in
a
group
or
result
set.
-
MIN():
Retrieves
the
minimum
value
in
a
group
or
result
set.
3.
DATA
MANIPULA TION
LANGUAGE
Data
Manipulation
Language
(DML)
in
SQL
encompasses
commands
that
manipulate
data
within
a
database.
DML
allows
you
to
insert,
update,
and
delete
records,
ensuring
the
accuracy
and
currency
of
your
data.
●
INSERT:
-
The
INSERT
statement
adds
new
records
to
a
table.
-
Syntax:
INSERT'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'of
your
data.
●
INSERT:
-
The
INSERT
statement
adds
new
records
to
a
table.
-
Syntax:
INSERT
INTO
table_name
(column1,
column2,
...)
VALUES
(value1,
value2,
...);
-
Example:
INSERT
INTO
employees
(first_name,
last_name,
salary)
VALUES
('John',
'Doe',
50000);
●
UPDATE
:
-
The
UPDATE
statement
modifies
existing
records
in
a
table.
-
Syntax:
UPDATE
table_name
SET
column1
=
value1,
column2
=
value2,
...
WHERE
condition;
-
Example:
UPDATE
employees
SET
salary
=
55000
WHERE
first_name
=
'John';
●'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'...
WHERE
condition;
-
Example:
UPDATE
employees
SET
salary
=
55000
WHERE
first_name
=
'John';
●
DELETE
:
-
The
DELETE
statement
removes
records
from
a
table.
-
Syntax:
DELETE
FROM
table_name
WHERE
condition;
-
Example:
DELETE
FROM
employees
WHERE
last_name
=
'Doe';
4.
Data
Control
Language
(DCL)'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'Data
Control
Language
focuses
on
the
management
of
access
rights,
permissions,
and
security-related
aspects
of
a
database
system.
DCL
commands
are
used
to
control
who
can
access
the
data,
modify
the
data,
or
perform
administrative
tasks
within
a
database.
DCL
is
an
important
aspect
of
database
security,
ensuring
that
data
remains
protected
and
only
authorised
users
have
the
necessary
privileges.
There
are
two
main
DCL
commands
in
SQL:
GRANT
and
REVOKE.
1.
GRANT:
The
GRANT
command
is
used
to'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'There
are
two
main
DCL
commands
in
SQL:
GRANT
and
REVOKE.
1.
GRANT:
The
GRANT
command
is
used
to
provide
specific
privileges
or
permissions
to
users
or
roles.
Privileges
can
include
the
ability
to
perform
various
actions
on
tables,
views,
procedures,
and
other
database
objects.
Syntax:
GRANT
privilege_type
ON
object_name
TO
user_or_role;
In
this
syntax:
●
privilege_type
refers
to
the
specific
privilege
or
permission
being
granted
(e.g.,
SELECT,
INSERT,
UPDATE,
DELETE).
●
object_name
is
the
name'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'or
permission
being
granted
(e.g.,
SELECT,
INSERT,
UPDATE,
DELETE).
●
object_name
is
the
name
of
the
database
object
(e.g.,
table,
view)
to
which
the
privilege
is
being
granted.
●
user_or_role
is
the
name
of
the
user
or
role
that
is
being
granted
the
privilege.
Example:
Granting
SELECT
privilege
on
a
table
named
"Employees"
to
a
user
named
"Analyst":
GRANT
SELECT
ON
Employees
TO
Analyst;
2.
REVOKE:
The
REVOKE
command
is
used
to
remove
or
revoke
specific
privileges
or
permissions
that
have
been'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'The
REVOKE
command
is
used
to
remove
or
revoke
specific
privileges
or
permissions
that
have
been
previously
granted
to
users
or
roles.
Syntax:
REVOKE
privilege_type
ON
object_name'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'FROM
user_or_role;
In
this
syntax:
●
privilege_type
is
the
privilege
or
permission
being
revoked.
●
object_name
is
the
name
of
the
database
object
from
which
the
privilege
is
being
revoked.
●
user_or_role
is
the
name
of
the
user
or
role
from
which
the
privilege
is
being
revoked.
Example:
Revoking
the
SELECT
privilege
on
the
"Employees"
table
from
the
"Analyst"
user:
REVOKE
SELECT
ON
Employees
FROM
Analyst;
DCL
and
Database
Security:
DCL
plays
a
crucial
role
in
ensuring
the
security
and
integrity'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'Analyst;
DCL
and
Database
Security:
DCL
plays
a
crucial
role
in
ensuring

Token indices sequence length is longer than the specified maximum sequence length for this model (16270 > 1024). Running this sequence through the model will result in indexing errors

> Finished chain.


> Entering new StuffDocumentsChain chain...


> Entering new LLMChain chain...
Prompt after formatting:
 Provide the final summary of entire speech
speech:'## Speech Summary:

**What is a Database?**

* A database is a collection of interconnected data.


**What is a DBMS?**

* A DBMS (Database Management System) is software used to create, manage, and organize databases.


**What is an RDBMS?**

* An RDBMS (Relational Database Management System) is a DBMS based on the concept of tables (relations) with rows (records) and columns (attributes).
* Popular examples include MySQL, PostgreSQL, and Oracle.


**What is SQL?**

* SQL (Structured Query Language) is a language used to interact with databases. It is used for:
    * Creating and modifying database structures
    * Inserting, updating, and deleting data
    * Retrieving data from databases

**Speech Summary:**

SQL (Structured Query Language) is a language used to interact with Relational Database Management Systems (RDBMS). It enables users to:

- **Store** data in databases.
- **Manipulate** existing data.
- **Retrieve** data from databases.

**Key Features:**

- SQL is not a database itself, but a language used to interact with databases.
- It is used for CRUD (Create, Read, Update, Delete) operations.
- SQL commands are used to create, alter, and delete databases, tables, and data.

**Examples of RDBMS that support SQL:**

- MySQL
- PostgreSQL
- Oracle

**Common SQL Commands:**

- **CREATE:** Creates databases, tables, and data.
- **READ:** Reads data from databases.
- **UPDATE:** Modifies existing data.
- **DELETE:** Deletes databases, tables, or data.

**Summary:**

The speech outlines two essential SQL commands for data manipulation: **UPDATE** and **DELETE**.

**UPDATE command:**

- Allows modifying existing data in a database.
- Uses commands to insert new data after modification.


**DELETE command:**

- Allows deleting data from a database.
- Can be used to delete:
    - An entire database
    - A specific table
    - A specific data point/tuple/row
    - Multiple rows


**Additional notes:**

- SQL keywords are not case-sensitive.
- SQL is a language used for performing CRUD (Create, Read, Update, Delete) operations in relational databases.
- MySQL is a specific relational database management system (RDBMS) that uses SQL.

**Summary:**

The speech discusses the concept of data types in SQL. Data types define the kind of data that can be stored in a column or variable.

**Key points:**

* Data types are essential for ensuring data integrity and allowing different operations on data.
* MySQL provides a variety of data types, including fixed-length strings (CHAR), variable-length strings (VARCHAR), binary large objects (BLOB), and integers (INT).
* The data type chosen should be appropriate for the type of data being stored.
* A list of commonly used SQL data types is provided, along with their descriptions and usage examples.

**Additional information:**

* The speech includes a link to the MySQL documentation on data types for more details.
* The speech emphasizes the importance of selecting the right data type to ensure efficient storage and retrieval of data.

**Summary:**

The speech outlines the data types supported in a specific database system. It covers:

- **Text-related:**
    - VARCHAR (variable-length string)
    - STRING (fixed-length string)
    - BLOB (Binary Large Object)


- **Numeric-related:**
    - INT (integer)
    - TINYINT (small integer)
    - BIGINT (large integer)
    - FLOAT (floating-point number)
    - DOUBLE (double-precision floating-point number)


- **Logical-related:**
    - BIT (binary value, either 0 or 1)


- **Date-related:**
    - DATE (date in YYYY-MM-DD format)


**Additional Details:**

- Some data types have size limitations (e.g., VARCHAR has a maximum length of 65535 characters).
- Some data types have a range of values (e.g., INT can range from -2,147,483,648 to 2,147,483,647).
- Certain data types support precision and precision-precision pairs (e.g., FLOAT with precision and digits).

**Summary:**

The speech outlines the different data types available in a specific system, including:

* **BOOLEAN:** A data type that can hold only two values: 0 or 1.


* **DATE:** A data type representing a specific date in the format YYYY-MM-DD.


* **TIME:** A data type representing a specific time in the format HH:MM:SS.


* **YEAR:** A data type representing a specific year in the format YYYY.


* **CHAR/VARCHAR:** Data types for storing fixed or variable length strings of characters, respectively.


* **UNSIGNED:** A modifier that indicates that the data type can only hold positive values.


**Key Points:**

- VARCHAR is generally better than CHAR as it only occupies necessary memory.
- We can use UNUNSIGNED with data types when we only have positive values.
- Examples of data types include BOOLEAN, DATE, TIME, YEAR, CHAR/VARCHAR, and UNUNSIGNED.

**Speech Summary:**

The speech highlights the use of **UNSIGNED data types** in SQL when only positive values need to be added.

**Key Points:**

* **Unsigned data types** in SQL are appropriate when only positive values are allowed in a column.
* **INT** is an unsigned integer data type that can hold non-negative integer values.
* The speech provides an example of using an **UNSIGNED INT** data type to store positive values.

**Example:**

```sql
UNSIGNED INT
```

**Purpose of Using Unsigned Data Types:**

* Ensures that only positive values can be stored, preventing invalid or unexpected data.
* Improves performance by reducing the need for range checking.

**When to Choose Unsigned Data Types:**

* When only positive values are allowed in a column.
* To optimize performance when dealing with large numbers of positive values.

**Benefits of Using Unsigned Data Types:**

* Reduced storage space requirements compared to signed data types.
* Improved performance due to efficient handling of positive values.

**Summary:**

The presented text outlines the different types of SQL (Structured Query Language) statements categorized based on their primary functions:

**1. DQL (Data Query Language)**
- Used to retrieve data from databases.
- Includes the SELECT statement.


**2. DDL (Data Definition Language)**
- Used to create, alter, and delete database objects.
- Includes commands like CREATE, DROP, ALTER, RENAME, and TRUNCATE.


**3. DML (Data Manipulation Language)**
- Used to modify the database.
- Includes statements for insertion, updating, and deleting data.


**4. DCL (Data Control Language)**
- Used to control access to database objects by granting and revoking permissions.
- Includes commands like GRANT and REVOKE.


**5. TCL (Transaction Control Language)**
- Used to manage transactions, which are groups of multiple database operations treated as a single unit.
- Includes commands like COMMIT and ROLLBACK.

**Speech Summary:**

The speech discusses two key components of the Structured Query Language (SQL): **Data Definition Language (DDL)** and **Transaction Control Language (TCL)**.

**Data Definition Language (DDL):**

* DDL is a subset of SQL used for defining and managing the structure of databases and their objects.
* It allows users to create, modify, and delete database objects such as tables, indexes, and constraints.

**Transaction Control Language (TCL):**

* TCL commands are used to manage transactions, which are sequences of multiple SQL statements treated as a single unit.
* Commands like COMMIT, ROLLBACK, START TRANSACTION, and SAVEPOINT are used to control the execution and integrity of transactions.

**Examples of DDL commands:**

* CREATE TABLE
* ALTER TABLE
* DROP TABLE

**Examples of TCL commands:**

* COMMIT
* ROLLBACK
* START TRANSACTION
* SAVEPOINT

**In summary:**

DDL commands are used for defining and managing the structure of databases, while TCL commands are used for controlling the execution and integrity of transactions.

## Speech Summary: Indexes, Constraints, and More

This speech outlines the three commands related to table manipulation in a database: **CREATE TABLE**, **ALTER TABLE**, and **DROP TABLE**.

**CREATE TABLE:**

- Used to create a new table in the database.
- Specifies the table name, column names, data types, constraints, and other properties.
- Example: Creating a table named "employees" with id, name, and salary columns.

**ALTER TABLE:**

- Used to modify the structure of an existing table.
- Allows adding, modifying, or dropping columns, constraints, and other elements.
- Example: Adding an email column to the "employees" table.

**DROP TABLE:**

- Used to delete a table from the database.


**Key Concepts:**

- **Constraints:** Rules that ensure data integrity and consistency in the database.
- **Indexes:** Structures that improve performance by speeding up searches and retrievals.


**Additional Information:**

- The speech provides specific examples for each command.
- The speech covers other aspects related to table manipulation, such as constraints and indexes.

The speech outlines two SQL commands: **ALTER TABLE** and **DROP TABLE**.

**ALTER TABLE:**

- Used to add a new column named "email" to the "employees" table.
- The data type of the new column is specified as "VARCHAR(100)".

**DROP TABLE:**

- Used to delete the "employees" table, including all its data and structure.


**In summary, the speech explains how to:**

- Add a new column to an existing table.
- Delete an existing table and its data.

## Speech Summary:

**Indexes and Constraints in SQL**

This speech explains how to create, drop, and define constraints in SQL.

**Index Creation:**

* Indexes improve query performance by enabling faster data retrieval.
* An index can be created on one or more columns in a table.
* Example: Creating an index on the `name` column of the `employees` table:

```sql
CREATE INDEX idx_employee_name ON employees (name);
```

**Index Removal:**

* Indexes can be removed using the `DROP INDEX` command.
* Example: Removing the `idx_employee_name` index from the `employees` table:

```sql
DROP INDEX idx_employee_name;
```

**Constraint Definition:**

* Constraints ensure data integrity by establishing rules for data entry.
* Different constraints exist such as primary key, foreign key, unique, not null, and check.
* Example: Adding a primary key constraint to the `orders` table:

```sql
ALTER TABLE orders ADD PRIMARY KEY (order_id);
```

**Summary:**

This speech covers the essential concepts of creating, removing, and defining constraints in SQL, highlighting their importance in optimizing query performance and ensuring data integrity.'


> Finished chain.

> Finished chain.


> Entering new StuffDocumentsChain chain...


> Entering new LLMChain chain...
Prompt after formatting:
 Provide the final summary of entire speech
speech:'## Summary of Speech: Constraints in SQL

This speech discusses different constraints that can be used in SQL to ensure data integrity and consistency.

**Types of constraints:**

* **PRIMARY KEY:** Ensures that a column or combination of columns is unique for each row in a table.
* **FOREIGN KEY:** Ensures that a column references the primary key of another table, ensuring data integrity.
* **UNIQUE:** Ensures that a column contains unique values within a table.
* **NOT NULL:** Ensures that a column cannot be left empty.
* **CHECK:** Ensures that a column meets specific criteria, such as range or data type.


**Commands for manipulating constraints:**

* **ADD CONSTRAINT:** Creates a new constraint on a table.
* **DROP CONSTRAINT:** Removes an existing constraint from a table.
* **TRUNCATE TABLE:** Deletes all data from a table.

**Examples:**

The speech includes examples of creating and removing a foreign key constraint on the `orders` table referencing the `customers` table. It also demonstrates how to truncate the `orders` table.

**Summary:**

Syntax is a subset of the SQL language specifically focused on retrieving data from databases. The foundation of this syntax is the **SELECT** statement, which allows users to extract specific columns from a table.

**Key points:**

* Syntax includes commands like **TRUNCATE** to delete data and **DATA** to define the retrieval or update process.
* **DQL** (Data Query Language) is a subset of SQL dedicated to data retrieval.
* The **SELECT** statement is the core of DQL and enables users to select desired columns from a table.

## Speech Summary:

This speech explains the syntax and usage of the **SELECT** statement in a database.

**Key points:**

* **Selecting specific fields:**
    - List individual column names after the `SELECT` statement.
    - Use `*` to select all fields in the table.


* **Selecting from a table:**
    - Specify the table name after the `FROM` clause.


* **Filtering records:**
    - Use the `WHERE` clause to filter records based on a condition.
    - The condition can use various operators like `=`, `>`, and others.


**Examples:**

- Selecting specific columns: `SELECT CustomerName, City FROM Customers`
- Selecting all columns: `SELECT * FROM Customers`
- Selecting filtered rows: `SELECT * FROM Customers WHERE Country='Mexico'`

**Additional notes:**

- The speech clearly explains the syntax of the `SELECT` statement with examples.
- It also briefly mentions other operators that can be used in the `WHERE` clause.

**Speech Summary:**

The speech explains the use of the `WHERE` clause in SQL to filter records based on specific criteria.

**Key points:**

- The `WHERE` clause allows you to select rows from a table based on certain conditions.
- It uses operators such as `=`, `>`, `<`, `>=`, `<=`, and `<>` to compare values and filter records.
- The operators can be combined using `AND`, `OR`, and `NOT` to create complex conditions.
- The `AND` operator requires that all specified conditions be met to select a record.
- The `OR` operator selects records that satisfy any of the specified conditions.
- The `NOT` operator excludes records that meet the specified condition.

**Examples of conditions:**

- `Country='Mexico'` - Selects rows where the Country column is equal to 'Mexico'.
- `Salary > 5000` - Selects rows where the Salary column is greater than 5000.
- `Age >= 21 AND Country='United States'` - Selects rows where the Age column is greater than or equal to 21 and the Country column is equal to 'United States'.

**Note:**

- The speech also mentions alternative syntax for the `NOT equal` operator, which is `!=`.
- The `WHERE` clause can be combined with other clauses in SQL, such as `ORDER BY` and `LIMIT`.

**Summary:**

The speech explains the three logical operators used in conditional statements: AND, OR, and NOT.

* **AND operator:** Displays a record if all conditions connected by AND are TRUE.
* **OR operator:** Displays a record if any condition connected by OR is TRUE.
* **NOT operator:** Displays a record if the condition(s) connected by NOT are NOT TRUE.

**Summary:**

The provided text discusses different SELECT statement syntax used in SQL to retrieve data from a table based on conditions.

**Key Concepts:**

* **SELECT statement:** Used to retrieve data from a table.
* **Conditions:** Criteria used to filter rows based on specific criteria.
* **Logical operators:** AND and OR are used to combine multiple conditions.
* **NOT operator:** Negates a condition, excluding rows that meet the condition.
* **DISTINCT:** Removes duplicate rows from the query results.

**Examples:**

* **Basic SELECT statement:** Retrieves all rows from the Customers table.
* **Conditional SELECT statement:** Retrieves rows where Country is 'India' and City is 'Japan'.
* **OR condition:** Retrieves rows where Country is 'America' and City is either 'India' or 'Korea'.
* **NOT condition:** Retrieves rows where City is not 'New York'.
* **DISTINCT keyword:** Retrieves only unique rows from the results.

**Syntax:**

```sql
SELECT
<column list>
FROM
<table name>
WHERE
<condition>
[ORDER BY <column>]
[LIMIT <number>]
```

**Additional Notes:**

* The provided text includes an example of a SELECT statement retrieving all rows from the Customers table where Country is 'India' and City is 'Japan'.
* The use of conditions allows for selective retrieval of data based on specific criteria.
* The DISTINCT keyword can be used to eliminate duplicate rows from the results.

**Summary:**

The given speech outlines two SQL concepts: **DISTINCT** and **LIKE** operators.

**DISTINCT Operator:**

- Used to remove duplicate rows from query results.
- Syntax: `SELECT DISTINCT column1, column2 FROM table_name;`
- Removes rows with identical values in the specified columns.

**LIKE Operator:**

- Used to search for a specified pattern in a column.
- Syntax: `SELECT column FROM table_name WHERE column LIKE 'pattern';`
- Allows searching for values containing a specific pattern, using wildcards:
    - `%`: Represents zero, one, or multiple characters.
    - `_`: Represents one single character.

**Example:**

- The example shows how to use the LIKE operator to find all employees with first names starting with "J."

The provided text does not include a speech transcript or any text related to a speech, so I am unable to summarize it.

**Summary:**

The speech outlines different ways to use the LIKE operator in SQL to search for values based on specific criteria.

**Key Points:**

* **Like with wildcard (%):**
    - `LIKE 'a_%'`: Finds values that start with "a" and have at least 2 characters.
    - `LIKE 'a__%'`: Finds values that start with "a" and have at least 3 characters.


* **Like with ending character:**
    - `LIKE 'a%o'`: Finds values that start with "a" and end with "o".


* **Using the IN operator:**
    - Allows filtering results based on a list of values specified in the WHERE clause.


* **Using the BETWEEN operator:**
    - Filters results within a specified range.

**Example:**

The provided example shows how to use the IN operator to select products from a table where the `category_id` is in a specific list (1, 2, 3).

**Speech Summary:**

The provided text discusses various features and syntax elements in the **WHERE** clause of SQL:

**1. Filtering Data within a Specified Range:**

- The WHERE clause can be used to filter results based on a specified range of values.
- An example shows filtering orders between '2023-01-01' and '2023-06-30'.


**2. Checking for NULL Values:**

- The IS NULL operator checks for NULL values in the WHERE clause.
- An example shows selecting customers with a NULL email address.


**3. Renaming Columns/Expressions:**

- The AS keyword allows you to rename columns or expressions in the query results.
- This can improve readability and presentation of the data.


**4. Sorting Results:**

- The ORDER BY clause sorts the results of the query in a specified order.


**Key Concepts:**

- **Category ID Filtering:** Filtering rows based on category IDs 1, 2, and 3.
- **Date Range Filtering:** Selecting rows within a specific date range.
- **NULL Value Checking:** Identifying rows with missing values.
- **Column Renaming:** Assigning new names to columns or expressions.
- **Sorting Results:** Ordering the query results based on a specific criteria.

**Speech Summary:**

The speech explains the **ORDER BY** clause in SQL, which allows you to sort the results of a query based on one or more columns.

**Key Points:**

- The `ORDER BY` clause is used after the `SELECT` statement to sort the query results.


- You can sort the results based on one or more columns.


- The basic syntax for the `ORDER BY` clause is:

```sql
ORDER BY column_name ASC | DESC
```

- `ASC` specifies that the results should be sorted in ascending order.
- `DESC` specifies that the results should be sorted in descending order.

**Example:**

```sql
SELECT *
FROM employees
ORDER BY salary DESC;
```

This query will select all rows from the `employees` table and sort them in descending order of salary.


'## Summary of Speech:\n\nThe speech focuses on **advanced SQL concepts** related to data retrieval and manipulation.\n\n**Main Topics:**\n\n* **Subqueries:** Nested queries used for retrieving and manipulating data.\n* **Joins:** Combining rows from multiple tables based on a common field.\n\n\n**Key Concepts:**\n\n* **Correlated subqueries:** Subqueries that reference columns from the outer query for filtering or sorting.\n* **Self joins:** Joins a table to itself, enabling comparisons between rows.\n* **Cross joins:** Creates a Cartesian product of two tables, resulting in a large dataset.\n\n\n**Examples:**\n\n- Finding customers with orders using a correlated subquery.\n- Performing an inner join to find employees and their managers.\n- Performing a left join to include all employees, even those without orders.\n\n\n**Performance Considerations:**\n\n- Subqueries can be slower for large datasets.\n- Joins can be computationally expensive for large datasets.\n\n\n**Conclusion:**\n\nAdvanced SQL concepts like subqueries and joins are essential for efficient data retrieval and manipulation in complex scenarios. Understanding these concepts allows for effective data management and analysis.'

Refine CHain summary

In [41]:
chain1=load_summarize_chain(model,chain_type='refine',verbose=True)
output_res1=summary_chain.run(final_docs)
output_res1

> Entering new MapReduceDocumentsChain chain...


> Entering new LLMChain chain...
Prompt after formatting:

Please summarize the speech
speech:'SQL
(Notes
by
Apna
College)
What
is
Database?
Database
is
a
collection
of
interrelated
data.
What
is
DBMS?
DBMS
(
Database
Management
System
)
is
software
used
to
create,
manage,
and
organize
databases.
What
is
RDBMS?
●
RDBMS
(Relational
Database
Management
System)
-
is
a
DBMS
based
on
the
concept
of
tables
(also
called
relations).
●
Data
is
organized
into
tables
(also
known
as
relations)
with
rows
(records)
and
columns
(attributes).
●
Eg
-
MySQL,
PostgreSQL,
Oracle
etc.
What
is
SQL?
SQL
is'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'rows
(records)
and
columns
(attributes).
●
Eg
-
MySQL,
PostgreSQL,
Oracle
etc.
What
is
SQL?
SQL
is
Structured
Query
Language
-
used
to
store,
manipulate
and
retrieve
data
from
RDBMS.
(It
is
not
a
database,
it
is
a
language
used
to
interact
with
database)
We
use
SQL
for
CRUD
Operations
:
●
CREATE
-
To
create
databases,
tables,
insert
tuples
in
tables
etc
●
READ
-
To
read
data
present
in
the
database.
●
UPDATE
-
Modify
already
inserted
data.
●
DELETE
-
Delete
database,
table
or
specific
data'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'●
UPDATE
-
Modify
already
inserted
data.
●
DELETE
-
Delete
database,
table
or
specific
data
point/tuple/row
or
multiple
rows.
*Note
-
SQL
keywords
are
NOT
case
sensitive.
Eg:
select
is
the
same
as
SELECT
in
SQL.
SQL
v/s
MySQL
SQL
is
a
language
used
to
perform
CRUD
operations
in
Relational
DB,
while
MySQL
is
a
RDBMS
that
uses
SQL.'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'SQL
Data
Types
In
SQL,
data
types
define
the
kind
of
data
that
can
be
stored
in
a
column
or
variable.
To
See
all
data
types
of
MYSQL,
visit
:
https://dev.mysql.com/doc/refman/8.0/en/data-types.html
Here
are
the
frequently
used
SQL
data
types:
DATATYPE
DESCRIPTION
USAGE
CHAR
string(0-255),
can
store
characters
of
fixed
length
CHAR(50)
VARCHAR
string(0-255),
can
store
characters
up
to
given
length
VARCHAR(50)
BLOB
string(0-65535),
can
store
binary
large
object
BLOB(1000)
INT
integer('
Summary:

Prompt after formatting:

Please summarize the speech
speech:'length
VARCHAR(50)
BLOB
string(0-65535),
can
store
binary
large
object
BLOB(1000)
INT
integer(
-2,147,483,648
to
2,147,483,647
)
INT
TINYINT
integer(-128
to
127)
TINYINT
BIGINT
integer(
-9,223,372,036,854,775,808
to
9,223,372,036,854,775,807
)
BIGINT
BIT
can
store
x-bit
values.
x
can
range
from
1
to
64
BIT(2)
FLOAT
Decimal
number
-
with
precision
to
23
digits
FLOAT
DOUBLE
Decimal
number
-
with
24
to
53
digits
DOUBLE
BOOLEAN
Boolean
values
0
or
1
BOOLEAN
DATE
date
in
format
of
YYYY-MM-DD'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'with
24
to
53
digits
DOUBLE
BOOLEAN
Boolean
values
0
or
1
BOOLEAN
DATE
date
in
format
of
YYYY-MM-DD
ranging
from
1000-01-01
to
9999-12-31
DATE
TIME
HH:MM:SS
TIME
YEAR
year
in
4
digits
format
ranging
from
1901
to
2155
YEAR
*Note
-
CHAR
is
for
fixed
length
&
VARCHAR
is
for
variable
length
strings.
Generally,
VARCHAR
is
better
as
it
only
occupies
necessary
memory
&
works
more
efficiently.
We
can
also
use
UNSIGNED
with
datatypes
when
we
only
have
positive
values
to
add.
Eg
-
UNSIGNED
INT
Types
of'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'use
UNSIGNED
with
datatypes
when
we
only
have
positive
values
to
add.
Eg
-
UNSIGNED
INT
Types
of
SQL
Commands:'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'1.
DQL
(Data
Query
Language)
:
Used
to
retrieve
data
from
databases.
(SELECT)
2.
DDL
(Data
Definition
Language)
:
Used
to
create,
alter,
and
delete
database
objects
like
tables,
indexes,
etc.
(CREATE,
DROP,
ALTER,
RENAME,
TRUNCATE)
3.
DML
(Data
Manipulation
Language)
:
Used
to
modify
the
database.
(INSERT,
UPDATE,
DELETE)
4.
DCL
(Data
Control
Language)
:
Used
to
grant
&
revoke
permissions.
(GRANT,
REVOKE)
5.
TCL
(Transaction
Control
Language)
:
Used
to
manage
transactions.
(COMMIT,
ROLLBACK,'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'REVOKE)
5.
TCL
(Transaction
Control
Language)
:
Used
to
manage
transactions.
(COMMIT,
ROLLBACK,
START
TRANSACTIONS,
SAVEPOINT)
1.
Data
Definition
Language
(DDL)
Data
Definition
Language
(DDL)
is
a
subset
of
SQL
(Structured
Query
Language)
responsible
for
defining
and
managing
the
structure
of
databases
and
their
objects.
DDL
commands
enable
you
to
create,
modify,
and
delete
database
objects
like
tables,
indexes,
constraints,
and
more.
Key
DDL
Commands
are:
●
CREATE
TABLE:
○
Used
to
create
a
new'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'indexes,
constraints,
and
more.
Key
DDL
Commands
are:
●
CREATE
TABLE:
○
Used
to
create
a
new
table
in
the
database.
○
Specifies
the
table
name,
column
names,
data
types,
constraints,
and
more.
○
Example:
CREATE
TABLE
employees
(id
INT
PRIMARY
KEY,
name
VARCHAR(50),
salary
DECIMAL(10,
2));
●
ALTER
TABLE:
○
Used
to
modify
the
structure
of
an
existing
table.
○
You
can
add,
modify,
or
drop
columns,
constraints,
and
more.
○
Example:
ALTER
TABLE
employees
ADD
COLUMN
email
VARCHAR(100);
●
DROP
TABLE:'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'and
more.
○
Example:
ALTER
TABLE
employees
ADD
COLUMN
email
VARCHAR(100);
●
DROP
TABLE:
○
Used
to
delete
an
existing
table
along
with
its
data
and
structure.
○
Example:
DROP
TABLE
employees;'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'●
CREATE
INDEX:
○
Used
to
create
an
index
on
one
or
more
columns
in
a
table.
○
Improves
query
performance
by
enabling
faster
data
retrieval.
○
Example:
CREATE
INDEX
idx_employee_name
ON
employees
(name);
●
DROP
INDEX:
○
Used
to
remove
an
existing
index
from
a
table.
○
Example:
DROP
INDEX
idx_employee_name;
●
CREATE
CONSTRAINT:
○
Used
to
define
constraints
that
ensure
data
integrity.
○
Constraints
include
PRIMARY
KEY,
FOREIGN
KEY,
UNIQUE,
NOT
NULL,
and
CHECK.
○
Example:
ALTER
TABLE
orders
ADD'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'include
PRIMARY
KEY,
FOREIGN
KEY,
UNIQUE,
NOT
NULL,
and
CHECK.
○
Example:
ALTER
TABLE
orders
ADD
CONSTRAINT
fk_customer
FOREIGN
KEY
(customer_id)
REFERENCES
customers(id);
●
DROP
CONSTRAINT:
○
Used
to
remove
an
existing
constraint
from
a
table.
○
Example:
ALTER
TABLE
orders
DROP
CONSTRAINT
fk_customer;
●
TRUNCATE
TABLE:
○
Used
to
delete
the
data
inside
a
table,
but
not
the
table
itself.
○
Syntax
–
TRUNCATE
TABLE
table_name
2.
DATA
QUER Y/RETRIEV AL
LANGUAGE
(DQL
or
DRL)
DQL
(Data
Query'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'Syntax
–
TRUNCATE
TABLE
table_name
2.
DATA
QUER Y/RETRIEV AL
LANGUAGE
(DQL
or
DRL)
DQL
(Data
Query
Language)
is
a
subset
of
SQL
focused
on
retrieving
data
from
databases.
The
SELECT
statement
is
the
foundation
of
DQL
and
allows
us
to
extract
specific
columns
from
a
table.
●
SELECT:
The
SELECT
statement
is
used
to
select
data
from
a
database.'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'Syntax:
SELECT
column1,
column2,
...
FROM
table_name;
Here,
column1,
column2,
...
are
the
field
names
of
the
table.
If
you
want
to
select
all
the
fields
available
in
the
table,
use
the
following
syntax:
SELECT
*
FROM
table_name;
Ex:
SELECT
CustomerName,
City
FROM
Customers;
●
WHERE:
The
WHERE
clause
is
used
to
filter
records.
Syntax:
SELECT
column1,
column2,
...
FROM
table_name
WHERE
condition;
Ex:
SELECT
*
FROM
Customers
WHERE
Country='Mexico';
Operators
used
in
WHERE
are:
=
:
Equal
>
:
Greater'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'SELECT
*
FROM
Customers
WHERE
Country='Mexico';
Operators
used
in
WHERE
are:
=
:
Equal
>
:
Greater
than
<
:
Less
than
>=
:
Greater
than
or
equal
<=
:
Less
than
or
equal
<>
:
Not
equal.
Note:
In
some
versions
of
SQL
this
operator
may
be
written
as
!=
●
AND,
OR
and
NOT:
-
The
WHERE
clause
can
be
combined
with
AND,
OR,
and
NOT
operators.
-
The
AND
and
OR
operators
are
used
to
filter
records
based
on
more
than
one
condition:
-
The
AND
operator
displays
a
record
if
all
the
conditions
separated
by'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'on
more
than
one
condition:
-
The
AND
operator
displays
a
record
if
all
the
conditions
separated
by
AND
are
TRUE.
-
The
OR
operator
displays
a
record
if
any
of
the
conditions
separated
by
OR
is
TRUE.
-
The
NOT
operator
displays
a
record
if
the
condition(s)
is
NOT
TRUE.
Syntax:'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'SELECT
column1,
column2,
...
FROM
table_name
WHERE
condition1
AND
condition2
AND
condition3
...;
SELECT
column1,
column2,
...
FROM
table_name
WHERE
condition1
OR
condition2
OR
condition3
...;
SELECT
column1,
column2,
...
FROM
table_name
WHERE
NOT
condition;
Example:
SELECT
*
FROM
Customers
WHERE
Country=’India’
AND
City=’Japan’;
SELECT
*
FROM
Customers
WHERE
Country=’America’
AND
(City=’India’
OR
City=’Korea’);
●
DISTINCT:
Removes
duplicate
rows
from
query
results.
Syntax:
SELECT
DISTINCT'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'OR
City=’Korea’);
●
DISTINCT:
Removes
duplicate
rows
from
query
results.
Syntax:
SELECT
DISTINCT
column1,
column2
FROM
table_name;
●
LIKE
:
The
LIKE
operator
is
used
in
a
WHERE
clause
to
search
for
a
specified
pattern
in
a
column.
There
are
two
wildcards
often
used
in
conjunction
with
the
LIKE
operator:
-
The
percent
sign
(%)
represents
zero,
one,
or
multiple
characters
-
The
underscore
sign
(_)
represents
one,
single
character
Example:
SELECT
*
FROM
employees
WHERE
first_name
LIKE
'J%';
WHERE'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'represents
one,
single
character
Example:
SELECT
*
FROM
employees
WHERE
first_name
LIKE
'J%';
WHERE
CustomerName
LIKE
'a%'
-
Finds
any
values
that
start
with
"a"
WHERE
CustomerName
LIKE
'%a'
-
Finds
any
values
that
end
with
"a"
WHERE
CustomerName
LIKE
'%or%'
-
Finds
any
values
that
have
"or"
in
any
position
WHERE
CustomerName
LIKE
'_r%'
-
Finds
any
values
that
have
"r"
in
the
second
position'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'WHERE
CustomerName
LIKE
'a_%'
-
Finds
any
values
that
start
with
"a"
and
are
at
least
2
characters
in
length
WHERE
CustomerName
LIKE
'a__%'
-
Finds
any
values
that
start
with
"a"
and
are
at
least
3
characters
in
length
WHERE
ContactName
LIKE
'a%o'
-
Finds
any
values
that
start
with
"a"
and
ends
with
"o"
●
IN:
Filters
results
based
on
a
list
of
values
in
the
WHERE
clause.
Example:
SELECT
*
FROM
products
WHERE
category_id
IN
(1,
2,
3);
●
BETWEEN
:
Filters
results
within
a
specified
range
in
the'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'WHERE
category_id
IN
(1,
2,
3);
●
BETWEEN
:
Filters
results
within
a
specified
range
in
the
WHERE
clause.
Example:
SELECT
*
FROM
orders
WHERE
order_date
BETWEEN
'2023-01-01'
AND
'2023-06-30';
●
IS
NULL
:
Checks
for
NULL
values
in
the
WHERE
clause.
Example:
SELECT
*
FROM
customers
WHERE
email
IS
NULL;
●
AS
:
Renames
columns
or
expressions
in
query
results.
Example:
SELECT
first_name
AS
"First
Name",
last_name
AS
"Last
Name"
FROM
employees;
●
ORDER
BY
The
ORDER
BY
clause
allows
you
to
sort
the'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'last_name
AS
"Last
Name"
FROM
employees;
●
ORDER
BY
The
ORDER
BY
clause
allows
you
to
sort
the
result
set
of
a
query
based
on
one
or
more
columns.
Basic
Syntax:
-
The
ORDER
BY
clause
is
used
after
the
SELECT
statement
to
sort
query
results.'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'-
Syntax:
SELECT
column1,
column2
FROM
table_name
ORDER
BY
column1
[ASC|DESC];
Ascending
and
Descending
Order:
-
By
default,
the
ORDER
BY
clause
sorts
in
ascending
order
(smallest
to
largest).
-
You
can
explicitly
specify
descending
order
using
the
DESC
keyword.
-
Example:
SELECT
product_name,
price
FROM
products
ORDER
BY
price
DESC;
Sorting
by
Multiple
Columns:
-
You
can
sort
by
multiple
columns
by
listing
them
sequentially
in
the
ORDER
BY
clause.
-
Rows
are
first
sorted
based
on
the
first'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'by
listing
them
sequentially
in
the
ORDER
BY
clause.
-
Rows
are
first
sorted
based
on
the
first
column,
and
for
rows
with
equal
values,
subsequent
columns
are
used
for
further
sorting.
-
Example:
SELECT
first_name,
last_name
FROM
employees
ORDER
BY
last_name,
first_name;
Sorting
by
Expressions:
-
It's
possible
to
sort
by
calculated
expressions,
not
just
column
values.
-
Example:
SELECT
product_name,
price,
price
*
1.1
AS
discounted_price
FROM
products
ORDER
BY
discounted_price;
Sorting
NULL'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'price,
price
*
1.1
AS
discounted_price
FROM
products
ORDER
BY
discounted_price;
Sorting
NULL
Values:
-
By
default,
NULL
values
are
considered
the
smallest
in
ascending
order
and
the
largest
in
descending
order.
-
You
can
control
the
sorting
behaviour
of
NULL
values
using
the
NULLS
FIRST
or
NULLS
LAST
options.
-
Example:
SELECT
column_name
FROM
table_name
ORDER
BY
column_name
NULLS
LAST;
Sorting
by
Position:
-
Instead
of
specifying
column
names,
you
can
sort
by
column
positions
in
the
ORDER
BY'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'by
Position:
-
Instead
of
specifying
column
names,
you
can
sort
by
column
positions
in
the
ORDER
BY
clause.
-
Example:
SELECT
product_name,
price
FROM
products
ORDER
BY
2
DESC,
1
ASC;
●
GROUP
BY
The
GROUP
BY
clause
in
SQL
is
used
to
group
rows
from
a
table
based
on
one
or
more
columns.
Syntax:'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'-
The
GROUP
BY
clause
follows
the
SELECT
statement
and
is
used
to
group
rows
based
on
specified
columns.
-
Syntax:
SELECT
column1,
aggregate_function(column2)
FROM
table_name
GROUP
BY
column1;
-
Aggregation
Functions:
○
Aggregation
functions
(e.g.,
COUNT,
SUM,
AVG,
MAX,
MIN)
are
often
used
with
GROUP
BY
to
calculate
values
for
each
group.
○
Example:
SELECT
department,
AVG(salary)
FROM
employees
GROUP
BY
department;
-
Grouping
by
Multiple
Columns:
○
You
can
group
by
multiple
columns
by
listing'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'GROUP
BY
department;
-
Grouping
by
Multiple
Columns:
○
You
can
group
by
multiple
columns
by
listing
them
in
the
GROUP
BY
clause.
○
This
creates
a
hierarchical
grouping
based
on
the
specified
columns.
○
Example:
SELECT
department,
gender,
AVG(salary)
FROM
employees
GROUP
BY
department,
gender;
-
HAVING
Clause:
○
The
HAVING
clause
is
used
with
GROUP
BY
to
filter
groups
based
on
aggregate
function
results.
○
It's
similar
to
the
WHERE
clause
but
operates
on
grouped
data.
○
Example:
SELECT'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'results.
○
It's
similar
to
the
WHERE
clause
but
operates
on
grouped
data.
○
Example:
SELECT
department,
AVG(salary)
FROM
employees
GROUP
BY
department
HAVING
AVG(salary)
>
50000;
-
Combining
GROUP
BY
and
ORDER
BY:
○
You
can
use
both
GROUP
BY
and
ORDER
BY
in
the
same
query
to
control
the
order
of
grouped
results.
○
Example:
SELECT
department,
COUNT(*)
FROM
employees
GROUP
BY
department
ORDER
BY
COUNT(*)
DESC;
●
AGGREGATE
FUNCTIONS
These
are
used
to
perform
calculations
on
groups
of
rows
or'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'BY
COUNT(*)
DESC;
●
AGGREGATE
FUNCTIONS
These
are
used
to
perform
calculations
on
groups
of
rows
or
entire
result
sets.
They
provide
insights
into
data
by
summarising
and
processing
information.
Common
Aggregate
Functions:
-
COUNT():
Counts
the
number
of
rows
in
a
group
or
result
set.
-
SUM():
Calculates
the
sum
of
numeric
values
in
a
group
or
result
set.
-
AVG():'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'Computes
the
average
of
numeric
values
in
a
group
or
result
set.
-
MAX():
Finds
the
maximum
value
in
a
group
or
result
set.
-
MIN():
Retrieves
the
minimum
value
in
a
group
or
result
set.
3.
DATA
MANIPULA TION
LANGUAGE
Data
Manipulation
Language
(DML)
in
SQL
encompasses
commands
that
manipulate
data
within
a
database.
DML
allows
you
to
insert,
update,
and
delete
records,
ensuring
the
accuracy
and
currency
of
your
data.
●
INSERT:
-
The
INSERT
statement
adds
new
records
to
a
table.
-
Syntax:
INSERT'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'of
your
data.
●
INSERT:
-
The
INSERT
statement
adds
new
records
to
a
table.
-
Syntax:
INSERT
INTO
table_name
(column1,
column2,
...)
VALUES
(value1,
value2,
...);
-
Example:
INSERT
INTO
employees
(first_name,
last_name,
salary)
VALUES
('John',
'Doe',
50000);
●
UPDATE
:
-
The
UPDATE
statement
modifies
existing
records
in
a
table.
-
Syntax:
UPDATE
table_name
SET
column1
=
value1,
column2
=
value2,
...
WHERE
condition;
-
Example:
UPDATE
employees
SET
salary
=
55000
WHERE
first_name
=
'John';
●'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'...
WHERE
condition;
-
Example:
UPDATE
employees
SET
salary
=
55000
WHERE
first_name
=
'John';
●
DELETE
:
-
The
DELETE
statement
removes
records
from
a
table.
-
Syntax:
DELETE
FROM
table_name
WHERE
condition;
-
Example:
DELETE
FROM
employees
WHERE
last_name
=
'Doe';
4.
Data
Control
Language
(DCL)'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'Data
Control
Language
focuses
on
the
management
of
access
rights,
permissions,
and
security-related
aspects
of
a
database
system.
DCL
commands
are
used
to
control
who
can
access
the
data,
modify
the
data,
or
perform
administrative
tasks
within
a
database.
DCL
is
an
important
aspect
of
database
security,
ensuring
that
data
remains
protected
and
only
authorised
users
have
the
necessary
privileges.
There
are
two
main
DCL
commands
in
SQL:
GRANT
and
REVOKE.
1.
GRANT:
The
GRANT
command
is
used
to'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'There
are
two
main
DCL
commands
in
SQL:
GRANT
and
REVOKE.
1.
GRANT:
The
GRANT
command
is
used
to
provide
specific
privileges
or
permissions
to
users
or
roles.
Privileges
can
include
the
ability
to
perform
various
actions
on
tables,
views,
procedures,
and
other
database
objects.
Syntax:
GRANT
privilege_type
ON
object_name
TO
user_or_role;
In
this
syntax:
●
privilege_type
refers
to
the
specific
privilege
or
permission
being
granted
(e.g.,
SELECT,
INSERT,
UPDATE,
DELETE).
●
object_name
is
the
name'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'or
permission
being
granted
(e.g.,
SELECT,
INSERT,
UPDATE,
DELETE).
●
object_name
is
the
name
of
the
database
object
(e.g.,
table,
view)
to
which
the
privilege
is
being
granted.
●
user_or_role
is
the
name
of
the
user
or
role
that
is
being
granted
the
privilege.
Example:
Granting
SELECT
privilege
on
a
table
named
"Employees"
to
a
user
named
"Analyst":
GRANT
SELECT
ON
Employees
TO
Analyst;
2.
REVOKE:
The
REVOKE
command
is
used
to
remove
or
revoke
specific
privileges
or
permissions
that
have
been'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'The
REVOKE
command
is
used
to
remove
or
revoke
specific
privileges
or
permissions
that
have
been
previously
granted
to
users
or
roles.
Syntax:
REVOKE
privilege_type
ON
object_name'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'FROM
user_or_role;
In
this
syntax:
●
privilege_type
is
the
privilege
or
permission
being
revoked.
●
object_name
is
the
name
of
the
database
object
from
which
the
privilege
is
being
revoked.
●
user_or_role
is
the
name
of
the
user
or
role
from
which
the
privilege
is
being
revoked.
Example:
Revoking
the
SELECT
privilege
on
the
"Employees"
table
from
the
"Analyst"
user:
REVOKE
SELECT
ON
Employees
FROM
Analyst;
DCL
and
Database
Security:
DCL
plays
a
crucial
role
in
ensuring
the
security
and
integrity'
Summary:

Prompt after formatting:

Please summarize the speech
speech:'Analyst;
DCL
and
Database
Security:
DCL
plays
a
crucial
role
in
ensuring

'## Summary of Speech: Indexes, Constraints, and Data Manipulation\n\n**Overall Topic:** Data management and optimization techniques in SQL.\n\n**Key Concepts:**\n\n* **Indexes:** Improve query performance by speeding up data retrieval.\n* **Constraints:** Ensure data integrity by defining rules for data entry.\n* **Outer Joins:** Combine data from multiple tables, including unmatched rows.\n* **Subqueries:** Retrieve data from one query and use it in another.\n\n\n**Main Points:**\n\n**1. Indexes:**\n\n- Created on columns to accelerate data retrieval.\n- Examples of creating and dropping indexes.\n\n\n**2. Constraints:**\n\n- Ensure data integrity by defining rules for data entry.\n- Different types: PRIMARY KEY, FOREIGN KEY, UNIQUE, NOT NULL, CHECK.\n\n\n**3. Outer Joins:**\n\n- Combine rows from multiple tables based on join conditions.\n- Different types: left outer join, right outer join, full outer join.\n\n\n**4. Subqueries:**\n\n- Retrieve data from one query and use it in another.\n- Useful for filtering, comparing, and calculating data.\n\n\n**5. Data Manipulation Techniques:**\n\n- Learn how to insert, update, and control data access.\n\n\n**Benefits of Efficient Data Management:**\n\n- Improved query performance.\n- Data integrity and completeness.\n- Efficient data retrieval and manipulation.\n\n\n**Applications:**\n\n- Data summarization and analysis.\n- Data security and access control.\n- Database management and optimization.\n\n**Conclusion:**\n\nUnderstanding data manipulation and retrieval techniques is crucial for effective data management in SQL.'